export type OutreachChannel = 'EMAIL' | 'MOBILE';
export type OutreachDraftStatus = 'DRAFT' | 'READY_FOR_OPERATOR' | 'APPROVED' | 'SENT' | 'MOBILE_CONFIRMED' | 'SUPERSEDED';
export interface OutreachQualityBinding { gateVersion: string; status: 'READY' | 'NEEDS_CORRECTION' | 'BLOCKED' | 'ABSTAIN'; decision: 'READY_FOR_OPERATOR' | 'REGENERATE' | 'BLOCKED' | 'ABSTAIN'; score: number | null; blockers: string[]; warnings: string[]; attempt: number; revision: number; fingerprint: string; }
export interface OutreachDraft { id: string; proposal_id: string; prospect_id: string; channel: OutreachChannel; recipient_ref: string; subject: string | null; body: string; proposal_link: string; revision: number; content_hash: string; quality?: OutreachQualityBinding | null; status: OutreachDraftStatus; approved_revision?: number | null; approved_hash?: string | null; }
export interface OutreachContacted { proposal_id: string; prospect_id: string; channel: OutreachChannel; contacted_at: string; draft_id: string; revision: number; fingerprint: string; message_id?: string | null; operator_id: string; }
export interface OutreachState { draft: OutreachDraft; contacted: OutreachContacted | null; }
export interface OutreachAction { ok: boolean; draftId: string; status?: string; revision?: number; fingerprint?: string; }
const isProduction = process.env.NODE_ENV === 'production';
const baseUrl = (process.env.NEXT_PUBLIC_MAGICSCRIPT_API_BASE_URL || process.env.MAGICSCRIPT_API_BASE_URL || (isProduction ? '' : 'http://127.0.0.1:8787')).replace(/\/$/, '');
const token = process.env.NEXT_PUBLIC_MAGICSCRIPT_API_TOKEN || process.env.MAGICSCRIPT_API_TOKEN || (isProduction ? undefined : 'dev-api-token');
function headers(): Headers { const value = new Headers({ 'content-type': 'application/json' }); if (token) value.set('authorization', `Bearer ${token}`); return value; }
export const outreachApiContract = { create: 'POST /api/v2/outreach/drafts', readByProposal: 'GET /api/v2/outreach/drafts/by-proposal/:proposalId?channel=:channel', read: 'GET /api/v2/outreach/drafts/:draftId', edit: 'POST /api/v2/outreach/drafts/:draftId/edit', approve: 'POST /api/v2/outreach/drafts/:draftId/approve', sendEmail: 'POST /api/v2/outreach/drafts/:draftId/send-email', confirmMobile: 'POST /api/v2/outreach/drafts/:draftId/confirm-manual-mobile' } as const;
async function request<T>(path: string, init?: RequestInit): Promise<T> { if (!baseUrl) throw new Error('Outreach API unavailable'); const response = await fetch(`${baseUrl}${path}`, { ...init, cache: 'no-store', headers: headers() }); if (!response.ok) { const text = await response.text(); throw new Error(response.status === 409 ? 'Cette révision n’est plus disponible. Rechargez le dossier.' : text || 'Action outreach impossible.'); } return await response.json() as T; }
export async function getOutreachDraft(id: string): Promise<OutreachState> { const payload = await request<{ draft: OutreachDraft; contacted?: OutreachContacted | null }>(`/api/v2/outreach/drafts/${encodeURIComponent(id)}`); return { draft: payload.draft, contacted: payload.contacted ?? null }; }
export async function getOutreachStateByProposal(proposalId: string, channel: OutreachChannel): Promise<OutreachState | null> { return request<OutreachState | null>(`/api/v2/outreach/drafts/by-proposal/${encodeURIComponent(proposalId)}?channel=${channel}`); }
async function reconcile(action: OutreachAction): Promise<OutreachState> { return getOutreachDraft(action.draftId); }
export async function createOutreachDraft(input: Record<string, unknown>): Promise<OutreachState> { return reconcile(await request('/api/v2/outreach/drafts', { method: 'POST', body: JSON.stringify(input) })); }
export async function editOutreachDraft(id: string, input: { subject?: string; body: string }): Promise<OutreachState> { return reconcile(await request(`/api/v2/outreach/drafts/${encodeURIComponent(id)}/edit`, { method: 'POST', body: JSON.stringify(input) })); }
export async function approveOutreachDraft(id: string, revision: number, fingerprint: string): Promise<OutreachState> { return reconcile(await request(`/api/v2/outreach/drafts/${encodeURIComponent(id)}/approve`, { method: 'POST', body: JSON.stringify({ revision, fingerprint }) })); }
export async function sendOutreachEmail(id: string): Promise<OutreachState> { return reconcile(await request(`/api/v2/outreach/drafts/${encodeURIComponent(id)}/send-email`, { method: 'POST', body: JSON.stringify({}) })); }
export async function confirmManualMobile(id: string, revision: number, fingerprint: string): Promise<OutreachState> { return reconcile(await request(`/api/v2/outreach/drafts/${encodeURIComponent(id)}/confirm-manual-mobile`, { method: 'POST', body: JSON.stringify({ revision, fingerprint }) })); }
