const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{DatabaseSync}=require('node:sqlite'),{execFileSync}=require('node:child_process'),assert=require('node:assert/strict');
const P='v2-51972816600033',dir=__dirname;
const DB=JSON.parse(fs.readFileSync('.r77z-runtime/preflight.json','utf8')).dbPath;
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const write=(n,v)=>fs.writeFileSync(path.join(dir,n),JSON.stringify(v,null,2)+'\n');
const fingerprint=root=>{const result={};for(const e of fs.readdirSync(root,{withFileTypes:true})){if(e.isDirectory())continue;assert(e.isFile());result[e.name]=sha(fs.readFileSync(path.join(root,e.name)));}return result;};
const files=()=>{const names=execFileSync('git',['ls-files','-z'],{encoding:'utf8'}).split('\0').filter(Boolean);return Object.fromEntries(names.filter(n=>fs.existsSync(n)&&fs.statSync(n).isFile()).map(n=>[n,sha(fs.readFileSync(n))]));};
const snapshot=()=>{const db=new DatabaseSync(DB,{readOnly:true});try{const r={};for(const t of ['prospects','v2_admissions','v2_design_requests','v2_design_artifacts','v2_design_reviews','v2_build_artifacts','v2_visual_qa_reports','v2_build_corrections','jobs'])r[t]=db.prepare(`SELECT * FROM ${t} WHERE ${t==='prospects'?'id':'prospect_id'}=? ORDER BY 1`).all(P);r.slot=db.prepare('SELECT * FROM active_production_slots WHERE prospect_id=?').get(P);return JSON.parse(JSON.stringify(r));}finally{db.close();}};
module.exports={P,DB,write,sha,fingerprint,files,snapshot};
if(require.main===module){const rows=snapshot();assert.equal(rows.v2_admissions.length,1);assert.equal(rows.slot.slot_id,2);assert.equal(rows.v2_build_artifacts.length,1);assert.equal(rows.v2_visual_qa_reports.length,1);assert.equal(rows.v2_build_corrections.length,0);assert(rows.jobs.every(j=>j.status==='SUCCEEDED'));assert.equal(rows.v2_design_reviews[0].decision,'APPROVE');const build=JSON.parse(rows.v2_build_artifacts[0].artifact_json);assert.equal(build.buildRevision,1);assert.equal(JSON.parse(rows.v2_design_artifacts[0].artifact_json).verticalProfile,'GENERAL_LOCAL_BUSINESS');write('preflight.json',{at:new Date().toISOString(),dbPath:DB,rows,build,r1Source:fingerprint(build.sourcePath),r1Output:fingerprint(build.outputPath),trackedFiles:files()});console.log(JSON.stringify({prospect:P,slot:rows.slot,build:build.id,revision:build.buildRevision,qa:rows.v2_visual_qa_reports[0].decision}));}
