import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {verifyBuildArtifactIntegrity} from '../core/builder/site-builder.ts';
import {normalizePublicVerticalLabelHtml,ensureLocalFaviconHtml,deterministicFaviconBytes} from '../core/builder/contracts.ts';
const require=createRequire(import.meta.url),{P,write,fingerprint,snapshot}=require('./preflight.cjs');
const dir='.r78z-runtime/',revision=Number(process.argv[2]);assert([2,3].includes(revision));
const read=(n:string)=>JSON.parse(fs.readFileSync(dir+n,'utf8').replace(/^\uFEFF/,''));const baseline=read('preflight.json'),stack=read('stack.json'),job=read(`correction-r${revision}-job.json`),cfg=JSON.parse(fs.readFileSync('apps/api-worker/wrangler.local.jsonc','utf8'));
assert(!fs.existsSync(dir+`runner-r${revision}-invocation.json`),'RUNNER_CONSUMED');
const before=snapshot();const pending=before.jobs.filter((j:any)=>j.kind==='V2_BUILD_CORRECTION'&&j.status==='PENDING');assert.equal(pending.length,1);assert.equal(pending[0].id,job.id);
const parent=revision===2?baseline.build:read('build-r2.json');await verifyBuildArtifactIntegrity(parent);
const rawFetch=globalThis.fetch;const health=await(await rawFetch(stack.apiUrl+'/health')).json();assert.equal(health.stackId,stack.stackId);assert.equal(health.effectiveOutboundMode,'disabled');assert.equal(health.prototypeDeployEnabled,false);
process.env.MAGICSCRIPT_STACK_ID=stack.stackId;process.env.MAGICSCRIPT_API_BASE_URL=stack.apiUrl;process.env.MAGICSCRIPT_RUNNER_TOKEN=cfg.vars.MAGICSCRIPT_RUNNER_TOKEN;process.env.MAGICSCRIPT_RUNNER_ID='r78z-androcam';process.env.MAGICSCRIPT_RUNNER_WORK_DIR=path.resolve(dir+'runner');process.env.MAGICSCRIPT_SENDING_ENABLED='false';process.env.MAGICSCRIPT_EMAIL_PROVIDER='disabled';process.env.MAGICSCRIPT_PROTOTYPE_DEPLOY_ENABLED='false';process.env.MAGICSCRIPT_PROTOTYPE_DEPLOY_MODE='mock';
let claims=0,success=0,fail=0;const calls:any[]=[];
globalThis.fetch=async(input:any,init:any)=>{const request=new Request(input,init),url=new URL(request.url);assert.equal(url.origin,stack.apiUrl,'NONLOCAL_OPERATION_FORBIDDEN');assert.equal(request.headers.get('x-magicscript-stack-id'),stack.stackId);const record:any={path:url.pathname,method:request.method,at:new Date().toISOString()};calls.push(record);if(url.pathname==='/api/runner/jobs/claim')assert.equal(++claims,1);if(url.pathname.endsWith('/succeed'))assert.equal(++success,1);if(url.pathname.endsWith('/fail'))fail++;const response=await rawFetch(request);record.status=response.status;if(url.pathname==='/api/runner/jobs/claim'&&response.ok&&response.status!==204){const claim=await response.clone().json();write(`claim-r${revision}.json`,claim);assert.equal(claim.job.id,job.id);assert.equal(claim.job.kind,'V2_BUILD_CORRECTION');assert.equal(claim.job.prospectId,P);}if(response.status>=400)record.error=await response.clone().text();write(`api-calls-r${revision}.json`,calls);return response;};
try{
 const {runOne}=await import('../apps/agent-runner/src/index.ts');write(`runner-r${revision}-invocation.json`,{at:new Date().toISOString(),jobId:job.id,realInvocations:1,stackId:stack.stackId});
 assert.equal(await runOne(),true);const after=snapshot();write(`post-build-r${revision}-rows.json`,after);const final=after.jobs.find((j:any)=>j.id===job.id);assert.equal(final.status,'SUCCEEDED',final.last_error);assert.equal(final.attempts,1);assert.equal(claims,1);assert.equal(success,1);assert.equal(fail,0);
 const row=after.v2_build_artifacts.find((b:any)=>b.build_revision===revision);assert(row);const build=JSON.parse(row.artifact_json);await verifyBuildArtifactIntegrity(build);assert.equal(build.buildRevision,revision);assert.equal(build.qaAttempt,revision);assert.equal(build.approvedRevision,1);assert.equal(build.previousBuildArtifactId,parent.id);assert.equal(build.correctionRequestId,read(`correction-r${revision}-request.json`).id);
 const oldHtml=fs.readFileSync(path.join(parent.sourcePath,'index.html'),'utf8'),html=fs.readFileSync(path.join(build.outputPath,'index.html'),'utf8');assert.equal(html,revision===2?normalizePublicVerticalLabelHtml(oldHtml,'GENERAL_LOCAL_BUSINESS'):ensureLocalFaviconHtml(oldHtml));assert(!html.includes('GENERAL_LOCAL_BUSINESS'));
 assert.deepEqual(fs.readFileSync(path.join(build.outputPath,'styles.css')),fs.readFileSync(path.join(parent.sourcePath,'styles.css')));
 if(revision===3)assert.deepEqual(fs.readFileSync(path.join(build.outputPath,'favicon.ico')),Buffer.from(deterministicFaviconBytes()));
 assert.deepEqual(fingerprint(baseline.build.sourcePath),baseline.r1Source);assert.deepEqual(fingerprint(baseline.build.outputPath),baseline.r1Output);assert.deepEqual(after.v2_build_artifacts.find((b:any)=>b.id===baseline.build.id),baseline.rows.v2_build_artifacts[0]);
 for(const t of ['v2_admissions','v2_design_requests','v2_design_artifacts','v2_design_reviews','v2_visual_qa_reports','v2_build_corrections','slot'])assert.deepEqual(after[t],before[t]);
 write(`build-r${revision}.json`,build);write(`build-r${revision}-result.json`,{status:'PASS',buildId:build.id,buildRevision:revision,qaAttempt:revision,designRevision:1,counts:{claims,success,fail},buildR1Immutable:true,job:final,slot:after.slot});console.log(JSON.stringify({status:'PASS',buildId:build.id,revision,qaAttempt:revision,jobStatus:final.status,buildR1Immutable:true}));
}catch(error){write(`build-r${revision}-error.json`,{at:new Date().toISOString(),error:error instanceof Error?error.stack:String(error)});throw error;}finally{globalThis.fetch=rawFetch;}
