import type { ProspectState } from '../types/prospect';

const allowedTransitions: Record<ProspectState, ProspectState[]> = {
  SAS_PENDING: [],
  DISCOVERED: ['RESEARCHING', 'DISQUALIFIED'],
  RESEARCHING: ['RESEARCH_COMPLETE', 'DISQUALIFIED'],
  RESEARCH_COMPLETE: ['QUALIFIED', 'DISQUALIFIED'],
  QUALIFIED: ['CONTACT_DISCOVERY', 'DISQUALIFIED'],
  DISQUALIFIED: [],
  CONTACT_DISCOVERY: ['CONTACT_FOUND', 'CONTACT_INVALID', 'DISQUALIFIED'],
  CONTACT_FOUND: ['PROTOTYPE_REQUIRED', 'OUTREACH_READY', 'DO_NOT_CONTACT'],
  CONTACT_INVALID: ['CONTACT_DISCOVERY', 'DISQUALIFIED'],
  OUTREACH_READY: ['OUTREACH_DRAFTED', 'HUMAN_ACTION_REQUIRED', 'DO_NOT_CONTACT'],
  OUTREACH_DRAFTED: ['OUTREACH_VERIFIED', 'OUTREACH_READY', 'HUMAN_ACTION_REQUIRED', 'DO_NOT_CONTACT'],
  OUTREACH_VERIFIED: ['EMAIL_SENT', 'HUMAN_ACTION_REQUIRED', 'DO_NOT_CONTACT'],
  EMAIL_SENT: ['WAITING_REPLY', 'REPLY_RECEIVED', 'BOUNCED'],
  WAITING_REPLY: ['FOLLOW_UP_DUE', 'REPLY_RECEIVED', 'BOUNCED', 'DO_NOT_CONTACT', 'INFORMATION_REQUEST_RECEIVED'],
  FOLLOW_UP_DUE: [
    'FOLLOW_UP_SENT',
    'REPLY_RECEIVED',
    'HUMAN_ACTION_REQUIRED',
    'DO_NOT_CONTACT',
  ],
  FOLLOW_UP_SENT: ['WAITING_REPLY', 'REPLY_RECEIVED', 'BOUNCED', 'DO_NOT_CONTACT'],
  REPLY_RECEIVED: [
    'WAITING_REPLY',
    'POSITIVE_REPLY',
    'INTERESTED',
    'NEGATIVE_REPLY',
    'HOT_LEAD',
    'MEETING_REQUESTED',
    'PRICING_REQUESTED',
    'CUSTOM_REQUEST',
    'HUMAN_ACTION_REQUIRED',
    'DO_NOT_CONTACT',
  ],
  POSITIVE_REPLY: [
    'INTERESTED',
    'MEETING_REQUESTED',
    'PRICING_REQUESTED',
    'CUSTOM_REQUEST',
  ],
  NEGATIVE_REPLY: ['DO_NOT_CONTACT', 'CLOSED_LOST'],
  BOUNCED: ['CONTACT_DISCOVERY', 'CLOSED_LOST'],
  DO_NOT_CONTACT: [],
  PROTOTYPE_REQUIRED: ['PROTOTYPE_STRATEGY_GENERATED', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_BUILDING: ['PROTOTYPE_QA', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_STRATEGY_GENERATED: ['PROTOTYPE_BUILDING', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_QA: [
    'PROTOTYPE_READY',
    'PROTOTYPE_REQUIRED',
    'PROTOTYPE_BUILDING',
    'HUMAN_ACTION_REQUIRED',
  ],
  PROTOTYPE_READY: ['PROTOTYPE_DEPLOYING', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_DEPLOYING: ['PROTOTYPE_DEPLOYED', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_DEPLOYED: [
    'OUTREACH_READY',
    'DEMO_REPLY_READY',
    'INTERESTED',
    'HUMAN_ACTION_REQUIRED',
  ],
  DEMO_REPLY_READY: ['DEMO_REPLY_SENT', 'DO_NOT_CONTACT', 'HUMAN_ACTION_REQUIRED'],
  DEMO_REPLY_SENT: ['WAITING_REPLY', 'REPLY_RECEIVED', 'BOUNCED', 'DO_NOT_CONTACT'],
  HOT_LEAD: ['MEETING_REQUESTED', 'PRICING_REQUESTED', 'CUSTOM_REQUEST', 'HUMAN_ACTION_REQUIRED'],
  MEETING_REQUESTED: ['HUMAN_ACTION_REQUIRED', 'MEETING_BOOKED', 'INTERESTED'],
  PRICING_REQUESTED: ['HUMAN_ACTION_REQUIRED'],
  CUSTOM_REQUEST: ['HUMAN_ACTION_REQUIRED'],
  INTERESTED: ['REPLY_RECEIVED', 'MEETING_BOOKED', 'QUOTE_PENDING', 'DORMANT', 'DO_NOT_CONTACT'],
  MEETING_BOOKED: ['INTERESTED', 'QUOTE_PENDING', 'DO_NOT_CONTACT'],
  QUOTE_PENDING: ['COMMITTED', 'DO_NOT_CONTACT'],
  COMMITTED: ['WON', 'DO_NOT_CONTACT'],
  WON: [],
  DORMANT: ['REPLY_RECEIVED', 'INTERESTED', 'DO_NOT_CONTACT'],
  HUMAN_ACTION_REQUIRED: [
    'CONTACT_DISCOVERY',
    'PROTOTYPE_REQUIRED',
    'OUTREACH_READY',
    'CLOSED_LOST',
  ],
  CLOSED_WON: [],
  CLOSED_LOST: [],
  INFORMATION_REQUEST_RECEIVED: [
  'INFORMATION_RESPONSE_DRAFTED',
  'HUMAN_ACTION_REQUIRED',
  'DO_NOT_CONTACT',
],
INFORMATION_RESPONSE_DRAFTED: [
  'INFORMATION_RESPONSE_VERIFIED',
  'HUMAN_ACTION_REQUIRED',
  'DO_NOT_CONTACT',
],
INFORMATION_RESPONSE_VERIFIED: [
  'WAITING_REPLY',
  'HUMAN_ACTION_REQUIRED',
  'DO_NOT_CONTACT',
],
};

export function canTransition(from: ProspectState, to: ProspectState): boolean {
  return allowedTransitions[from].includes(to);
}

export function assertTransition(from: ProspectState, to: ProspectState): void {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid prospect state transition: ${from} -> ${to}`);
  }
}

export { allowedTransitions };
