import type { ProspectState } from '../types/prospect';

const allowedTransitions: Record<ProspectState, ProspectState[]> = {
  DISCOVERED: ['RESEARCHING', 'DISQUALIFIED'],
  RESEARCHING: ['RESEARCH_COMPLETE', 'DISQUALIFIED'],
  RESEARCH_COMPLETE: ['QUALIFIED', 'DISQUALIFIED'],
  QUALIFIED: ['CONTACT_DISCOVERY', 'DISQUALIFIED'],
  DISQUALIFIED: [],
  CONTACT_DISCOVERY: ['CONTACT_FOUND', 'CONTACT_INVALID', 'DISQUALIFIED'],
  CONTACT_FOUND: ['OUTREACH_READY', 'DO_NOT_CONTACT'],
  CONTACT_INVALID: ['CONTACT_DISCOVERY', 'DISQUALIFIED'],
  OUTREACH_READY: ['EMAIL_SENT', 'DO_NOT_CONTACT'],
  EMAIL_SENT: ['WAITING_REPLY', 'BOUNCED'],
  WAITING_REPLY: [
    'FOLLOW_UP_DUE',
    'POSITIVE_REPLY',
    'NEGATIVE_REPLY',
    'BOUNCED',
    'DO_NOT_CONTACT',
  ],
  FOLLOW_UP_DUE: ['FOLLOW_UP_SENT', 'DO_NOT_CONTACT'],
  FOLLOW_UP_SENT: [
    'WAITING_REPLY',
    'POSITIVE_REPLY',
    'NEGATIVE_REPLY',
    'BOUNCED',
    'DO_NOT_CONTACT',
  ],
  POSITIVE_REPLY: [
    'PROTOTYPE_REQUIRED',
    'HOT_LEAD',
    'MEETING_REQUESTED',
    'PRICING_REQUESTED',
    'CUSTOM_REQUEST',
  ],
  NEGATIVE_REPLY: ['DO_NOT_CONTACT', 'CLOSED_LOST'],
  BOUNCED: ['CONTACT_DISCOVERY', 'CLOSED_LOST'],
  DO_NOT_CONTACT: [],
  PROTOTYPE_REQUIRED: ['PROTOTYPE_BUILDING', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_BUILDING: ['PROTOTYPE_QA', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_QA: ['PROTOTYPE_READY', 'PROTOTYPE_BUILDING', 'HUMAN_ACTION_REQUIRED'],
  PROTOTYPE_READY: ['HOT_LEAD', 'WAITING_REPLY', 'HUMAN_ACTION_REQUIRED'],
  HOT_LEAD: ['MEETING_REQUESTED', 'PRICING_REQUESTED', 'CUSTOM_REQUEST', 'HUMAN_ACTION_REQUIRED'],
  MEETING_REQUESTED: ['HUMAN_ACTION_REQUIRED'],
  PRICING_REQUESTED: ['HUMAN_ACTION_REQUIRED'],
  CUSTOM_REQUEST: ['HUMAN_ACTION_REQUIRED'],
  HUMAN_ACTION_REQUIRED: ['CLOSED_WON', 'CLOSED_LOST'],
  CLOSED_WON: [],
  CLOSED_LOST: [],
};

export function canTransition(from: ProspectState, to: ProspectState): boolean {
  return allowedTransitions[from].includes(to);
}

export function assertTransition(from: ProspectState, to: ProspectState): void {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid prospect state transition: ${from} -> ${to}`);
  }
}

export { allowedTransitions };
