"use client";
import { useMemo, useState } from 'react';
import OutreachReview from './OutreachReview';
import type { ProposalDeckItemV1, DeckCommercialStage } from '../lib/deck';

const filters: Array<[string, DeckCommercialStage]> = [['À contacter','A_CONTACTER'],['Envoyés','ENVOYES'],['En attente','EN_ATTENTE'],['RDV','RDV'],['Devis','DEVIS'],['Relances','RELANCES'],['Gagnés','GAGNES'],['Perdus','PERDUS'],['Archivés','ARCHIVES']];
const labels: Record<DeckCommercialStage, string> = Object.fromEntries(filters) as Record<DeckCommercialStage, string>;
const stateLabels: Record<string, string> = { PROTOTYPE_REQUIRED: 'Démo en préparation', PROTOTYPE_READY: 'Démo prête', PROTOTYPE_DEPLOYED: 'Démo prête', DEMO_REPLY_READY: 'Message prêt', EMAIL_SENT: 'Envoyé', CONTACTED: 'Envoyé', WAITING_REPLY: 'En attente', MEETING_BOOKED: 'Rendez-vous prévu', MEETING_REQUESTED: 'Rendez-vous demandé', QUOTE_PENDING: 'Devis à préparer', FOLLOW_UP_DUE: 'Relance due', FOLLOW_UP_SENT: 'Relance envoyée', WON: 'Gagné', CLOSED_WON: 'Gagné', NEGATIVE_REPLY: 'Perdu', CLOSED_LOST: 'Perdu', DISQUALIFIED: 'Perdu', DO_NOT_CONTACT: 'Perdu', DORMANT: 'Relance' };
function hasProposal(item: ProposalDeckItemV1): item is ProposalDeckItemV1 & { proposal: NonNullable<ProposalDeckItemV1['proposal']> } {
  return item.proposal !== undefined;
}
function Row({ item }: { item: ProposalDeckItemV1 }) {
  const signals = [item.engagement.viewed ? 'Proposal consultée' : '', item.engagement.returned ? 'Retour reçu' : '', item.engagement.meetingBooked ? 'Rendez-vous prévu' : ''].filter(Boolean);
  return <article className="prospect-row"><div className="prospect-identity"><p className="row-label">{item.currentMeaningfulState ? stateLabels[item.currentMeaningfulState] || labels[item.commercialStage || 'A_CONTACTER'] : 'État non disponible'}</p><h2>{item.businessName}</h2><p className="identity">{[item.vertical, item.location].filter(Boolean).join(' · ') || 'Activité non renseignée'}</p></div><div className="prospect-detail"><span className="detail-label">Canaux</span><span>{item.contactability.label}</span></div><div className="prospect-detail"><span className="detail-label">Signal récent</span><span>{item.latestMeaningfulAction || signals.at(-1) || 'Aucun signal récent'}</span></div><div className="prospect-detail next-action"><span className="detail-label">Prochaine action</span><span>{item.nextMeaningfulOperatorAction || (item.proposal ? 'Consulter la Proposal' : 'Aucune action disponible')}</span></div>{item.proposal ? <a className="open-action" href={item.proposalUrl || item.proposal.entryPath} target="_blank" rel="noreferrer">OUVRIR <span aria-hidden="true">↗</span></a> : <span className="open-action">OUVRIR</span>}<div className="row-signals" aria-label="Signaux commerciaux">{signals.map((value) => <span key={value} className="signal">{value}</span>)}</div>{hasProposal(item) ? <OutreachReview item={item} /> : null}</article>;
}
export default function DeckPipeline({ items }: { items: ProposalDeckItemV1[] }) {
  const [stage, setStage] = useState<DeckCommercialStage>('A_CONTACTER'); const [search, setSearch] = useState('');
  const counts = useMemo(() => filters.reduce((out, [, key]) => ({ ...out, [key]: items.filter((item) => key === 'A_CONTACTER' ? item.activeSlot === true : item.commercialStage === key).length }), {} as Record<string, number>), [items]);
  const visible = items.filter((item) => (stage === 'A_CONTACTER' ? item.activeSlot === true : item.commercialStage === stage) && [item.businessName, item.vertical, item.location].filter(Boolean).join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  return <><div className="pipeline-filters" role="group" aria-label="Filtres du pipeline">{filters.map(([label, key]) => <button type="button" className={stage === key ? 'pipeline-filter active' : 'pipeline-filter'} key={key} onClick={() => setStage(key)}>{label} <span>{counts[key]}</span></button>)}</div><label className="sr-only" htmlFor="deck-search">Rechercher un prospect</label><input id="deck-search" className="deck-list-search" type="search" placeholder="Filtrer les prospects" value={search} onChange={(event) => setSearch(event.target.value)} />{visible.length ? visible.map((item) => <Row key={item.prospectId} item={item} />) : <section className="state-panel"><h2>Aucun prospect à afficher</h2><p>Aucun prospect canonique dans cette étape.</p></section>}</>;
}
