"use client";
import { useEffect, useMemo, useState } from "react";
import type { ProposalDeckItemV1 } from "../lib/deck";
import { approveOutreachDraft, confirmManualMobile, createOutreachDraft, editOutreachDraft, getOutreachDraft, getOutreachStateByProposal, sendOutreachEmail, type OutreachState } from "../lib/outreach";
type Channel = "EMAIL" | "MOBILE";
function fallbackBody(item: ProposalDeckItemV1) { return `Bonjour,\n\nEn regardant ${item.businessName}, nous avons relevé : ${item.opportunity || "une opportunité d’amélioration du parcours client"}.\n\nNous avons préparé une proposition concrète pour votre activité : ${item.proposalUrl || item.proposal.entryPath}\n\nBien à vous,\nMagic Script`; }
export default function OutreachReview({ item }: { item: ProposalDeckItemV1 }) {
  const defaultChannel: Channel | null = item.contactability.email ? "EMAIL" : item.contactability.mobile ? "MOBILE" : null;
  const [channel, setChannel] = useState<Channel | null>(defaultChannel); const [state, setState] = useState<OutreachState | null>(null); const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [copied, setCopied] = useState(false);
  const draft = state?.draft ?? null; const contacted = state?.contacted ?? null; const recipient = channel === "EMAIL" ? item.contactability.email : item.contactability.mobile; const editable = draft?.status === "DRAFT" || draft?.status === "READY_FOR_OPERATOR"; const approved = draft?.status === "APPROVED"; const mailto = useMemo(() => recipient && channel === "EMAIL" ? `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}` : undefined, [body, channel, recipient, subject]);
  useEffect(() => { let cancelled = false; async function load() { if (!defaultChannel) return; setLoading(true); try { const existing = await getOutreachStateByProposal(item.proposal.id, defaultChannel); const created = existing || await createOutreachDraft({ proposalId: item.proposal.id, channel: defaultChannel, recipientRef: defaultChannel === "EMAIL" ? item.contactability.email : item.contactability.mobile, body: fallbackBody(item), subject: defaultChannel === "EMAIL" ? `Une proposition pour ${item.businessName}` : null, proposalLink: item.proposalUrl || item.proposal.entryPath }); if (!cancelled) { setState(created); setSubject(created.draft.subject || ""); setBody(created.draft.body); } } catch (e) { if (!cancelled) setError(e instanceof Error ? e.message : "Chargement impossible."); } finally { if (!cancelled) setLoading(false); } } void load(); return () => { cancelled = true; }; }, [defaultChannel, item]);
  async function mutate(action: () => Promise<OutreachState>) { setLoading(true); setError(null); try { const next = await action(); setState(next); setSubject(next.draft.subject || ""); setBody(next.draft.body); } catch (e) { setError(e instanceof Error ? e.message : "Action impossible."); } finally { setLoading(false); } }
  async function copy(value: string) { await navigator.clipboard?.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1200); }
  function changeChannel(next: Channel) { if (next === channel) return; setChannel(next); setState(null); setSubject(""); setBody(""); setError(null); }
  return <section className="outreach-review" aria-label={`Revue outreach ${item.businessName}`} data-outreach-status={contacted ? "CONTACTED" : draft?.status || "LOADING"}>
    <div className="outreach-review-heading"><div><p className="card-kicker">M010 · OUTREACH REVIEW</p><h3>Revoir le message avant action</h3></div><span className={approved ? "review-status approved" : "review-status"}>{approved ? "APPROUVÉ" : "À VALIDER"}</span></div>
    {!defaultChannel ? <p className="outreach-empty">Aucun canal public préparé.</p> : <>
      {loading && !draft ? <p role="status">Chargement du brouillon…</p> : null}{error ? <p className="state-panel error" role="alert">{error}</p> : null}{contacted ? <p className="contacted-status">Contacted · {contacted.channel}</p> : null}
      <div className="outreach-channel" role="group" aria-label="Canal outreach"><button type="button" className={channel === "EMAIL" ? "selected" : ""} disabled={!item.contactability.email || loading} onClick={() => changeChannel("EMAIL")}>Email</button><button type="button" className={channel === "MOBILE" ? "selected" : ""} disabled={!item.contactability.mobile || loading} onClick={() => changeChannel("MOBILE")}>Mobile</button></div>
      <p className="outreach-recipient"><strong>Destinataire</strong> {recipient || "Non disponible"}</p>{draft ? <p className="proposal-meta" data-draft-revision={`r${draft.revision}`}>Révision r{draft.revision} · {draft.content_hash}</p> : null}
      {channel === "EMAIL" ? <label className="outreach-field"><span>Objet</span><input value={subject} disabled={!editable || loading} onChange={e => setSubject(e.target.value)} /></label> : null}<label className="outreach-field"><span>{channel === "EMAIL" ? "Corps de l’email" : "Texte à lire / copier"}</span><textarea value={body} disabled={!editable || loading} onChange={e => setBody(e.target.value)} rows={7} /></label>
      <div className="approval-boundary"><strong>Approbation humaine requise</strong><span>La révision affichée vient du backend.</span></div><div className="outreach-actions">
        {channel === "MOBILE" ? <><button type="button" data-outreach-action="copy-message" className="copy-button" disabled={loading} onClick={() => void copy(body)}>Copier le message</button><button type="button" data-outreach-action="copy-number" className="copy-button" disabled={loading} onClick={() => void copy(recipient || "")}>Copier le numéro</button></> : null}
        {editable ? <button type="button" data-outreach-action="edit" className="approve-button" disabled={loading || !draft} onClick={() => void mutate(() => editOutreachDraft(draft!.id, { subject, body }))}>Enregistrer la révision</button> : null}
        {!approved && editable ? <button type="button" data-outreach-action="approve" className="approve-button" disabled={loading || !draft} onClick={() => void mutate(() => approveOutreachDraft(draft!.id, draft!.revision, draft!.content_hash))}>Approuver cette révision</button> : null}
        {channel === "EMAIL" ? <><button type="button" data-outreach-action="send-email" className="send-button" disabled={!approved || loading} onClick={() => void mutate(() => sendOutreachEmail(draft!.id))}>Envoyer l’email</button>{mailto ? <a className="copy-button" href={mailto}>Ouvrir un aperçu</a> : null}</> : <button type="button" data-outreach-action="confirm-mobile" className="send-button" disabled={!approved || loading || Boolean(contacted)} onClick={() => { if (window.confirm("Confirmer l’action mobile manuelle ? Aucun SMS ou WhatsApp ne sera envoyé.")) void mutate(() => confirmManualMobile(draft!.id, draft!.revision, draft!.content_hash)); }}>{contacted ? "Action mobile confirmée" : "Marquer comme contacté"}</button>}
      </div>{copied ? <p className="mobile-copy">Copié.</p> : null}
    </>}
  </section>;
}
