import LiveRefresh from '../components/LiveRefresh';
import DeckPipeline from '../components/DeckPipeline';
import DeckHeader from '../components/DeckHeader';
import { getProposalDeck } from '../lib/deck';
import { getSwarmSnapshot, type SwarmSnapshot } from '../lib/api';
import Swarm from '../components/Swarm';
export const dynamic = 'force-dynamic';
function TodayPanel({ activeSlotCount }: { activeSlotCount: number }) { return <section className="operator-panel today-panel" aria-labelledby="today-title"><div className="section-heading"><p className="overline">Opérateur</p><h2 id="today-title">Aujourd'hui</h2></div><div className="attention-list"><div><strong>{activeSlotCount} / 20</strong><span>À contacter</span></div><div><strong>—</strong><span>Relances dues</span></div><div><strong>—</strong><span>RDV aujourd'hui</span></div><div><strong>—</strong><span>Devis à valider</span></div></div></section>; }
function LivingHiveFrame({ snapshot }: { snapshot: SwarmSnapshot }) { return <section className="living-hive-frame" aria-labelledby="hive-title"><div className="hive-title"><p className="overline">Espace central</p><h2 id="hive-title">Living Hive</h2></div><Swarm snapshot={snapshot} /></section>; }
function UpcomingPanel() { return <aside className="operator-panel upcoming-panel" aria-label="Contexte opérateur à venir">{[['PROCHAINS RDV', 'Aucun rendez-vous à venir'], ['RELANCES DUES', 'Aucune relance à afficher'], ['SIGNAUX IMPORTANTS', 'Aucun signal important']].map(([title, empty]) => <section className="upcoming-section" key={title}><h2>{title}</h2><p>{empty}</p></section>)}</aside>; }
export default async function Page() { const [deck, swarm] = await Promise.all([getProposalDeck(), getSwarmSnapshot()]); return <main className="deck-shell deck-dashboard" id="top"><LiveRefresh intervalMs={5000} /><DeckHeader /><section className="cockpit-grid" aria-label="Cockpit opérateur"><TodayPanel activeSlotCount={deck.activeSlotCount} /><LivingHiveFrame snapshot={swarm} /><UpcomingPanel /></section><section className="pipeline-section" aria-labelledby="pipeline-title"><div className="section-heading inline-heading"><div><p className="overline">Vue commerciale</p><h2 id="pipeline-title">Pipeline</h2></div><span className="placeholder-note">Projection canonique</span></div>{deck.error ? <section className="state-panel error" role="alert"><h2>Deck indisponible</h2><p>{deck.error}</p></section> : <section className="prospect-list" aria-labelledby="prospects-title"><div className="section-heading inline-heading"><div><p className="overline">Travail en cours</p><h2 id="prospects-title">Prospects</h2></div><span className="placeholder-note">{deck.items.length} prospect{deck.items.length > 1 ? 's' : ''}</span></div><DeckPipeline items={deck.items} /></section>}</section></main>; }
