import LiveRefresh from '../components/LiveRefresh';
import DeckPipeline from '../components/DeckPipeline';
import { getProposalDeck } from '../lib/deck';
export const dynamic = 'force-dynamic';
function DeckHeader() { const destinations = ['Prospects', 'Rendez-vous', 'Améliorations', 'Archives', 'Ruche']; return <header className="deck-header"><a className="brand" href="#top" aria-label="Magic Script, accueil"><span className="brand-mark">✦</span><span>MAGIC SCRIPT</span></a><label className="search-field"><span className="sr-only">Rechercher un prospect</span><input type="search" placeholder="Rechercher un prospect" /></label><nav className="main-nav" aria-label="Navigation principale">{destinations.map((destination) => <span className={destination === 'Prospects' ? 'nav-item active' : 'nav-item'} key={destination}>{destination}</span>)}<a className="nav-item" href="/pain-first-intake">Intake manuel</a></nav></header>; }
function TodayPanel({ activeSlotCount }: { activeSlotCount: number }) { return <section className="operator-panel today-panel" aria-labelledby="today-title"><div className="section-heading"><p className="overline">Opérateur</p><h2 id="today-title">Aujourd'hui</h2></div><div className="attention-list"><div><strong>{activeSlotCount} / 20</strong><span>À contacter</span></div><div><strong>—</strong><span>Relances dues</span></div><div><strong>—</strong><span>RDV aujourd'hui</span></div><div><strong>—</strong><span>Devis à valider</span></div></div></section>; }
function LivingHiveFrame() { return <section className="living-hive-frame" aria-labelledby="hive-title"><div className="hive-title"><p className="overline">Espace central</p><h2 id="hive-title">Living Hive</h2></div><div className="hive-mount" aria-label="Zone de montage Living Hive" /></section>; }
function UpcomingPanel() { return <aside className="operator-panel upcoming-panel" aria-label="Contexte opérateur à venir">{[['PROCHAINS RDV', 'Aucun rendez-vous à venir'], ['RELANCES DUES', 'Aucune relance à afficher'], ['SIGNAUX IMPORTANTS', 'Aucun signal important']].map(([title, empty]) => <section className="upcoming-section" key={title}><h2>{title}</h2><p>{empty}</p></section>)}</aside>; }
export default async function Page() { const deck = await getProposalDeck(); return <main className="deck-shell" id="top"><LiveRefresh intervalMs={5000} /><DeckHeader /><section className="cockpit-grid" aria-label="Cockpit opérateur"><TodayPanel activeSlotCount={deck.activeSlotCount} /><LivingHiveFrame /><UpcomingPanel /></section><section className="pipeline-section" aria-labelledby="pipeline-title"><div className="section-heading inline-heading"><div><p className="overline">Vue commerciale</p><h2 id="pipeline-title">Pipeline</h2></div><span className="placeholder-note">Projection canonique</span></div>{deck.error ? <section className="state-panel error" role="alert"><h2>Deck indisponible</h2><p>{deck.error}</p></section> : <section className="prospect-list" aria-labelledby="prospects-title"><div className="section-heading inline-heading"><div><p className="overline">Travail en cours</p><h2 id="prospects-title">Prospects</h2></div><span className="placeholder-note">{deck.items.length} prospect{deck.items.length > 1 ? 's' : ''}</span></div><DeckPipeline items={deck.items} /></section>}</section></main>; }
