import type { SourceType, IdentityStatus } from './agent';
function stableHash(value:string):string { let h1=0x811c9dc5,h2=0x9e3779b9; for(let i=0;i<value.length;i++){const c=value.charCodeAt(i);h1=Math.imul(h1^c,16777619);h2=Math.imul(h2^c,2246822519);} return `${(h1>>>0).toString(16).padStart(8,'0')}${(h2>>>0).toString(16).padStart(8,'0')}`; }

export type TelemetrySelectionStatus = 'SELECTED' | 'NOT_SELECTED' | 'SKIPPED';
export type TelemetryFetchStatus = 'NOT_ATTEMPTED' | 'ATTEMPTED' | 'SUCCEEDED' | 'FAILED' | 'SKIPPED';
export type TelemetryIdentityStatus = 'NOT_EVALUATED' | 'VERIFIED' | 'PROBABLE' | 'AMBIGUOUS' | 'REJECTED';
export type TelemetryPathOrigin = 'DISCOVERED_LINK' | 'GENERATED_CONTACT_PATH' | 'GENERATED_LEGAL_PATH' | 'HOMEPAGE' | 'OTHER';
export interface SourceExtractionTelemetry { phoneObserved:boolean; phoneEvidenceTypes:string[]; emailObserved:boolean; emailEvidenceTypes:string[]; instagramObserved:boolean; facebookObserved:boolean; tiktokObserved:boolean; whatsappObserved:boolean; contactFormObserved:boolean; }
export interface SourceCanonicalizationTelemetry { phoneVerified:boolean; emailVerified:boolean; instagramVerified:boolean; facebookVerified:boolean; tiktokVerified:boolean; whatsappVerified:boolean; contactFormVerified:boolean; rejectionReasons:string[]; }
export interface SourceTelemetry { schemaVersion:'contact-source-telemetry.v1'; sourceId:string; prospectId:string; url:string; normalizedUrl:string; sourceType:SourceType; sourceOrigin:string; pathOrigin:TelemetryPathOrigin; candidateDiscovered:boolean; selectionStatus:TelemetrySelectionStatus; selectionReason:string; fetchStatus:TelemetryFetchStatus; fetchAttemptedAt:string|null; fetchCompletedAt:string|null; httpStatus:number|null; failureReason:string|null; contentType:string|null; responseBytes:number|null; redirectCount:number|null; identityStatus:TelemetryIdentityStatus; identityReason:string; extraction:SourceExtractionTelemetry; canonicalization:SourceCanonicalizationTelemetry; createdAt:string; updatedAt:string; }
export function sourceTelemetryId(prospectId:string,url:string):string { return `src-${stableHash(`${prospectId}\n${url}`)}`; }
export function pathOriginFor(sourceOrigin:string, sourceType:SourceType):TelemetryPathOrigin { if (sourceOrigin==='owned-site-exploration') return sourceType==='LEGAL_PAGE'?'GENERATED_LEGAL_PATH':'GENERATED_CONTACT_PATH'; if (sourceOrigin==='canonical.websiteUrl') return 'HOMEPAGE'; return 'DISCOVERED_LINK'; }
export function normalizeIdentityStatus(status:IdentityStatus|'NOT_EVALUATED'):TelemetryIdentityStatus { return status==='IDENTITY_VERIFIED'?'VERIFIED':status==='IDENTITY_PROBABLE'?'PROBABLE':status==='IDENTITY_AMBIGUOUS'?'AMBIGUOUS':status==='IDENTITY_REJECTED'?'REJECTED':'NOT_EVALUATED'; }
export function normalizeFailureReason(reason:string|null):string|null { if(!reason)return null; const x=reason.toUpperCase(); if(x.includes('403'))return 'HTTP_403';if(x.includes('404'))return 'HTTP_404';if(x.includes('429'))return 'HTTP_429';if(x.includes('503'))return 'HTTP_503';if(x.includes('TIMEOUT'))return 'TIMEOUT';if(x.includes('ENOTFOUND')||x.includes('DNS'))return 'DNS_FAILURE';if(x.includes('TLS')||x.includes('CERT'))return 'TLS_FAILURE';if(x.includes('REDIRECT'))return 'REDIRECT_FAILURE';if(x.includes('TOO_LARGE'))return 'RESPONSE_TOO_LARGE';if(x.includes('CONTENT_TYPE'))return 'UNSUPPORTED_CONTENT_TYPE';if(x.includes('PRIVATE')||x.includes('SSRF'))return 'SSRF_REJECTED';if(x.includes('FETCH_ERROR')||x.includes('FETCH FAILED'))return 'NETWORK_ERROR';return 'OTHER'; }
export function extractionFromPresence(p:any):SourceExtractionTelemetry { const field=(k:string)=>p?.[k]; const evidence=(k:string)=>Array.isArray(field(k)?.evidence)?field(k).evidence:[]; const types=(k:string)=>evidence(k).map((e:any)=>String(e.evidenceType||'UNKNOWN')); return {phoneObserved:evidence('phone').length>0,phoneEvidenceTypes:types('phone'),emailObserved:evidence('email').length>0,emailEvidenceTypes:types('email'),instagramObserved:evidence('instagram').length>0,facebookObserved:evidence('facebook').length>0,tiktokObserved:evidence('tiktok').length>0,whatsappObserved:evidence('whatsapp').length>0,contactFormObserved:evidence('contactForm').length>0}; }
export function canonicalizationFromPresence(p:any):SourceCanonicalizationTelemetry { const v=(k:string)=>fieldStatus(p,k)==='VERIFIED'; return {phoneVerified:v('phone'),emailVerified:v('email'),instagramVerified:v('instagram'),facebookVerified:v('facebook'),tiktokVerified:v('tiktok'),whatsappVerified:v('whatsapp'),contactFormVerified:v('contactForm'),rejectionReasons:Array.isArray(p?.reasons)?p.reasons.map(String):[]}; }
function fieldStatus(p:any,k:string){return p?.[k]?.status;}
