import fs from 'node:fs';
import assert from 'node:assert/strict';
import https from 'node:https';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {acceptPainFirstSearchCandidate} from '../core/research/pain-first-staging.ts';
import {createPainFirstLiveHomepageInspector} from '../core/research/pain-first-homepage-transport.ts';
const dir='.r75z-continuation2-runtime/';
const write=(n:string,v:unknown)=>fs.writeFileSync(dir+n,JSON.stringify(v,null,2)+'\n');
assert(!fs.existsSync(dir+'zakari-invocation.json'),'DIAGNOSIS_ALREADY_CONSUMED');
const prior=JSON.parse(fs.readFileSync('.r75z-continuation-runtime/preflight.json','utf8'));
const db=new DatabaseSync(prior.dbPath,{readOnly:true});
const snapshot=Object.fromEntries(Object.keys(prior.snapshot).map(t=>[t,db.prepare(`SELECT * FROM ${t} ORDER BY 1`).all()]));
db.close();
assert.equal(JSON.stringify(snapshot),JSON.stringify(prior.snapshot),'D1 baseline drift');
const diffHash=createHash('sha256').update(execFileSync('git',['diff','--binary'],{maxBuffer:20*1024*1024,stdio:['ignore','pipe','ignore']})).digest('hex');
write('preflight.json',{verifiedAt:new Date().toISOString(),dbPath:prior.dbPath,d1Sha256:createHash('sha256').update(JSON.stringify(snapshot)).digest('hex'),trackedDiffSha256:diffHash,d1MatchesPrior:true});
const candidate={...JSON.parse(fs.readFileSync('.r75z-runtime/candidate.json','utf8')).candidate,providerRunId:'R75Z-continuation2-diagnosis',acquiredAt:new Date().toISOString()};
const accepted=acceptPainFirstSearchCandidate(candidate);
assert.equal(accepted.state,'URL_ACCEPTED');
if(accepted.state!=='URL_ACCEPTED')throw new Error('REJECTED');
const diagnostics:any[]=[];const chunks:Buffer[]=[];let bytes=0;
const inspect=createPainFirstLiveHomepageInspector({httpsRequest:(options,cb)=>{
  diagnostics.push({stage:'REQUEST',hostname:options.hostname,path:options.path});
  const req=https.request(options,msg=>{
    diagnostics.push({stage:'RESPONSE',status:msg.statusCode,headers:Object.fromEntries(['content-type','content-length','content-encoding','content-disposition'].map(k=>[k,msg.headers[k]??null]))});
    msg.on('data',(chunk:Buffer)=>{bytes+=chunk.length;if(bytes<=350000)chunks.push(Buffer.from(chunk));});
    cb(msg);
  });
  req.once('socket',s=>s.once('secureConnect',()=>diagnostics.push({stage:'TLS',authorized:(s as any).authorized})));
  req.once('error',(e:any)=>diagnostics.push({stage:'ERROR',code:e.code,message:e.message}));
  return req;
}});
write('zakari-invocation.json',{startedAt:new Date().toISOString(),invocations:1,retries:0,purpose:'one rejection diagnosis'});
const result=await inspect(accepted);
fs.writeFileSync(dir+'zakari-response.bin',Buffer.concat(chunks));
write('zakari-inspection.json',result);write('zakari-diagnostics.json',{diagnostics,bytesObserved:bytes,bytesRetained:Buffer.concat(chunks).length});
console.log(JSON.stringify({pageState:result.pageState,httpResultClass:result.observation.httpResultClass,diagnostics,bytesObserved:bytes}));
