import type { ProspectState } from '../types/prospect';

export type NextAction =
  | 'RUN_RESEARCH_SWARM'
  | 'RUN_SCORING'
  | 'DISCOVER_CONTACT'
  | 'VALIDATE_CONTACT'
  | 'GENERATE_OUTREACH'
  | 'FACT_CHECK_OUTREACH'
  | 'SEND_EMAIL'
  | 'WAIT'
  | 'SCHEDULE_FOLLOW_UP'
  | 'SEND_FOLLOW_UP'
  | 'CLASSIFY_REPLY'
  | 'BUILD_PROTOTYPE'
  | 'RUN_PROTOTYPE_QA'
  | 'DEPLOY_PROTOTYPE'
  | 'SEND_DEMO_LINK'
  | 'ESCALATE_TO_HUMAN'
  | 'ARCHIVE'
  | 'STOP';

const stateToAction: Record<ProspectState, NextAction> = {
  DISCOVERED: 'RUN_RESEARCH_SWARM',
  RESEARCHING: 'WAIT',
  RESEARCH_COMPLETE: 'RUN_SCORING',
  QUALIFIED: 'DISCOVER_CONTACT',
  DISQUALIFIED: 'ARCHIVE',
  CONTACT_DISCOVERY: 'WAIT',
  CONTACT_FOUND: 'VALIDATE_CONTACT',
  CONTACT_INVALID: 'DISCOVER_CONTACT',
  OUTREACH_READY: 'GENERATE_OUTREACH',
  OUTREACH_DRAFTED: 'FACT_CHECK_OUTREACH',
  OUTREACH_VERIFIED: 'SEND_EMAIL',
  EMAIL_SENT: 'WAIT',
  WAITING_REPLY: 'WAIT',
  FOLLOW_UP_DUE: 'SEND_FOLLOW_UP',
  FOLLOW_UP_SENT: 'WAIT',
  REPLY_RECEIVED: 'CLASSIFY_REPLY',
  POSITIVE_REPLY: 'BUILD_PROTOTYPE',
  NEGATIVE_REPLY: 'ARCHIVE',
  BOUNCED: 'DISCOVER_CONTACT',
  DO_NOT_CONTACT: 'STOP',
  PROTOTYPE_REQUIRED: 'BUILD_PROTOTYPE',
  PROTOTYPE_BUILDING: 'WAIT',
  PROTOTYPE_QA: 'RUN_PROTOTYPE_QA',
  PROTOTYPE_READY: 'DEPLOY_PROTOTYPE',
  PROTOTYPE_DEPLOYING: 'WAIT',
  PROTOTYPE_DEPLOYED: 'WAIT',
  DEMO_REPLY_READY: 'SEND_DEMO_LINK',
  DEMO_REPLY_SENT: 'WAIT',
  HOT_LEAD: 'ESCALATE_TO_HUMAN',
  MEETING_REQUESTED: 'ESCALATE_TO_HUMAN',
  PRICING_REQUESTED: 'ESCALATE_TO_HUMAN',
  CUSTOM_REQUEST: 'ESCALATE_TO_HUMAN',
  HUMAN_ACTION_REQUIRED: 'ESCALATE_TO_HUMAN',
  CLOSED_WON: 'STOP',
  CLOSED_LOST: 'STOP',
};

export function getNextAction(state: ProspectState): NextAction {
  return stateToAction[state];
}
