import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { findPrototypeSourceFiles } from './prototype-source-files';

export type CreativeLoopStatus = 'PASS' | 'PASS_WITH_NOTES' | 'REWORK' | 'BLOCK';
export interface CreativeFinding { category: 'hierarchy' | 'typography' | 'spacing' | 'layout' | 'mobile' | 'cta' | 'density' | 'brand' | 'antiSlop'; severity: 'WARNING' | 'BLOCKING'; description: string; evidence: string; suggestedAction: string; }
export interface CreativeReview { status: CreativeLoopStatus; reviewType: 'CREATIVE_VISUAL'; findings: readonly CreativeFinding[]; reworkRequired: boolean; reworkSummary: string; filesChanged: readonly string[]; checkedAt: string; reviewer: 'BU Web Design'; verifier: 'runner-bounded-creative-v1'; }
function sourceSignals(source: string) { return { cards: (source.match(/card|grid|panel/gi) ?? []).length, hasCta: /contact|réserver|reserver|découvrir|decouvrir|demander/i.test(source), hasMediaQuery: /@media/.test(source), headingCount: (source.match(/<h[1-3]\b/gi) ?? []).length }; }
export async function reviewCreativePrototype(workDir: string, checkedAt = new Date().toISOString()): Promise<CreativeReview> { const files = await findPrototypeSourceFiles(workDir); const content = (await Promise.all(files.map(async (file) => { try { return await readFile(join(workDir, file), 'utf8'); } catch { return ''; } }))).join('\n'); const signals = sourceSignals(content); const findings: CreativeFinding[] = []; if (signals.cards >= 8) findings.push({ category: 'antiSlop', severity: 'BLOCKING', description: 'Repeated card/grid vocabulary suggests a flat card-wall composition.', evidence: `${signals.cards} card/grid/panel markers in source`, suggestedAction: 'Replace repetitive cards with stronger hierarchy.' }); if (signals.headingCount < 2) findings.push({ category: 'hierarchy', severity: 'BLOCKING', description: 'Insufficient heading hierarchy.', evidence: `${signals.headingCount} headings found`, suggestedAction: 'Add hierarchy without inventing facts.' }); if (!signals.hasCta) findings.push({ category: 'cta', severity: 'BLOCKING', description: 'No recognizable primary CTA.', evidence: 'No grounded CTA label found', suggestedAction: 'Expose a verified or safe generic CTA.' }); if (!signals.hasMediaQuery) findings.push({ category: 'mobile', severity: 'WARNING', description: 'No mobile media query found.', evidence: 'No @media rule found', suggestedAction: 'Add bounded mobile rules.' }); const blocking = findings.some((finding) => finding.severity === 'BLOCKING'); return { status: blocking ? 'REWORK' : findings.length ? 'PASS_WITH_NOTES' : 'PASS', reviewType: 'CREATIVE_VISUAL', findings, reworkRequired: blocking, reworkSummary: blocking ? 'Bounded local visual rework required.' : 'No blocking creative findings remain.', filesChanged: [], checkedAt, reviewer: 'BU Web Design', verifier: 'runner-bounded-creative-v1' }; }
export async function applyBoundedCreativeRework(workDir: string, review: CreativeReview): Promise<CreativeReview> { if (!review.reworkRequired) return review; const target = join(workDir, 'app', 'globals.css'); let css: string; try { css = await readFile(target, 'utf8'); } catch { return { ...review, status: 'BLOCK', reworkSummary: 'Writable local stylesheet not found.' }; } const marker = '/* MAGIC_SCRIPT_BOUNDED_CREATIVE_REWORK_V1 */'; if (!css.includes(marker)) { css = `${css.trimEnd()}\n\n${marker}\n:root { --ms-space-section: clamp(3rem, 9vw, 7rem); }\nmain { max-width: 72rem; margin-inline: auto; padding-inline: 1.25rem; }\nsection { margin-block: var(--ms-space-section); }\nh1, h2 { text-wrap: balance; }\n@media (max-width: 40rem) { main { padding-inline: 1rem; } }\n`; await writeFile(target, css, 'utf8'); } return { ...review, status: 'PASS_WITH_NOTES', reworkRequired: false, reworkSummary: 'Bounded local hierarchy, spacing, and mobile rework applied.', filesChanged: ['app/globals.css'] }; }
export async function runCreativeReviewReworkLoop(workDir: string): Promise<{ before: CreativeReview; after: CreativeReview; rebuilt: boolean }> { const before = await reviewCreativePrototype(workDir); if (!before.reworkRequired) return { before, after: before, rebuilt: false }; const changed = await applyBoundedCreativeRework(workDir, before); const after = await reviewCreativePrototype(workDir); return { before, after: { ...after, filesChanged: changed.filesChanged }, rebuilt: true }; }
