import fs from 'node:fs';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { buildDeterministicArtifact, executeVerticalDesigner, InMemoryDesignArtifactStore } from '../core/design/design-artifact.ts';
import { executeBuilder, InMemoryBuildArtifactStore } from '../core/builder/site-builder.ts';
import { createBuildCorrectionRequest, executeVisualQa } from '../core/visual-qa/engine.ts';
import { InMemoryBuildCorrectionStore, InMemoryVisualQaReportStore } from '../core/visual-qa/contracts.ts';
import { runBrowserQa } from './m007-browser-qa.cjs';

const repo = resolve('.'); const root = join(repo, 'artifacts', 'v2'); const buildRoot = join(root, 'sites'); const qaRoot = join(root, 'qa', 'm007r-final');
const dist = join(buildRoot, 'prospect-m007-cafe', 'artifact-dr-m007-cafe-design_request_v1-design_artifact_v1-r1', 'dist'); const resultPath = join(root, 'qa', 'm007r-final-acceptance.json');
const request: any = { id: 'dr-m007-cafe-DESIGN_REQUEST_V1', version: 'DESIGN_REQUEST_V1', prospectId: 'prospect-m007-cafe', admission: { packId: 'pack-m007-cafe', schemaVersion: 'CONTACT_OPPORTUNITY_PACK_V2' }, identity: { businessName: 'Café Rivage' }, opportunity: { businessContext: 'Local café' }, designInput: { businessVertical: 'RESTAURANT', evidence: [{ url: 'https://example.test', note: 'verified identity', supports: ['identity'] }] }, createdAt: '2026-01-01T00:00:00.000Z' };
const check = (x: unknown, message: string) => { if (!x) throw new Error(message); };
const evidence = (browser: any, overflow?: number) => ({ viewports: browser.viewports.map((v: any) => ({ name: v.viewport.width === 1440 ? 'DESKTOP' : 'MOBILE', width: v.viewport.width, height: v.viewport.height, horizontalOverflow: overflow ?? v.viewport.horizontalOverflow, heroVisible: v.viewport.heroVisible, primaryCtaVisible: v.viewport.primaryCtaVisible, contentVisible: v.viewport.contentVisible, controlsWithinViewport: v.viewport.controlsWithinViewport })), observedSections: ['hero', 'menu-or-offer', 'visit-information', 'location-and-contact'], brokenAssets: [], internalLinkErrors: [], consoleErrors: [], unresolvedMarkers: [], headings: ['h1 Café Rivage'] });
async function main() {
  await rm(qaRoot, { recursive: true, force: true }); await mkdir(qaRoot, { recursive: true });
  const design: any = { ...buildDeterministicArtifact(request, request.createdAt), status: 'APPROVED' }; const builds = new InMemoryBuildArtifactStore();
  const build = await executeBuilder({ artifact: design, designRequest: request, root: buildRoot, store: builds }); check(build.status === 'SUCCEEDED' && build.version === 'BUILD_ARTIFACT_V1', 'M006 build did not succeed'); check(build.outputPath === dist && fs.existsSync(join(dist, 'index.html')), 'genuine M006 dist missing');
  const buildReplay = await executeBuilder({ artifact: design, designRequest: request, root: buildRoot, store: builds }); check(buildReplay.id === build.id && (await builds.list()).length === 1, 'Builder replay failed');
  const good = await runBrowserQa({ root: dist, outputDir: join(qaRoot, 'good'), primaryCta: design.strategy.primaryCta, viewports: ['DESKTOP', 'MOBILE'] }); const qa = new InMemoryVisualQaReportStore(); const corrections = new InMemoryBuildCorrectionStore();
  const goodReport = await executeVisualQa({ build, design, request, evidence: evidence(good), attempt: 1, store: qa }); check(goodReport.decision === 'PASS', `good build decision ${goodReport.decision}`); await writeFile(join(qaRoot, 'qa-report-good.json'), JSON.stringify(goodReport, null, 2));
  const defectRoot = join(qaRoot, 'defect-dist'); await cp(dist, defectRoot, { recursive: true }); await writeFile(join(defectRoot, 'styles.css'), `${await readFile(join(defectRoot, 'styles.css'), 'utf8')}\nbody{min-width:500px}\n`);
  const defect = await runBrowserQa({ root: defectRoot, outputDir: join(qaRoot, 'defect'), primaryCta: design.strategy.primaryCta, viewports: ['MOBILE'] }); check(defect.viewports[0].viewport.horizontalOverflow > 1, 'browser did not measure injected overflow'); const defectReport = await executeVisualQa({ build, design, request, evidence: evidence(defect, defect.viewports[0].viewport.horizontalOverflow), attempt: 1 }); check(defectReport.decision === 'CORRECTION_REQUIRED' && defectReport.issues.some((i) => i.category === 'RESPONSIVE_LAYOUT'), 'defect did not produce responsive correction');
  const correction = createBuildCorrectionRequest(defectReport); await corrections.save(correction); await corrections.save(correction); await writeFile(join(qaRoot, 'build-correction-request.json'), JSON.stringify(correction, null, 2)); check((await corrections.list()).length === 1, 'correction replay duplicated');
  const designStore = new InMemoryDesignArtifactStore(); await designStore.save(design); const generated: any = await executeVerticalDesigner({ request, artifacts: designStore, previousArtifact: design, correction: { corrections: [{ targetArea: correction.issue.category, requiredChange: correction.issue.expectedCorrection }] }, revision: 2 }); const correctedDesign: any = { ...generated, status: 'APPROVED' }; const correctedBuild = await executeBuilder({ artifact: correctedDesign, designRequest: request, root: buildRoot, store: builds }); check(correctedBuild.status === 'SUCCEEDED' && correctedBuild.approvedRevision === 2, 'corrected Builder build failed');
  const corrected = await runBrowserQa({ root: correctedBuild.outputPath, outputDir: join(qaRoot, 'corrected'), primaryCta: correctedDesign.strategy.primaryCta, viewports: ['DESKTOP', 'MOBILE'] }); const correctedReport = await executeVisualQa({ build: correctedBuild, design: correctedDesign, request, evidence: evidence(corrected), attempt: 1, store: qa }); check(correctedReport.decision === 'PASS', `corrected decision ${correctedReport.decision}`); await writeFile(join(qaRoot, 'qa-report-corrected.json'), JSON.stringify(correctedReport, null, 2));
  const replay = await executeVisualQa({ build, design, request, evidence: evidence(good), attempt: 1, store: qa }); check(replay.id === goodReport.id && (await qa.list()).length === 2, 'QA replay duplicated'); const limits = []; for (let attempt = 1; attempt <= 3; attempt += 1) limits.push(await executeVisualQa({ build, design, request, evidence: { ...evidence(defect, 110), unresolvedMarkers: ['debug'] }, attempt })); check(limits.map((x) => x.decision).join(',') === 'CORRECTION_REQUIRED,CORRECTION_REQUIRED,VISUAL_QA_LIMIT_REACHED', 'QA limit behavior failed');
  const final = { status: 'PASS', browser: good.browser, build: { id: build.id, outputPath: build.outputPath, correctedId: correctedBuild.id }, browserProof: { previewUrls: [good.previewUrl, defect.previewUrl, corrected.previewUrl], desktop: good.viewports.find((v: any) => v.viewport.width === 1440), mobile: good.viewports.find((v: any) => v.viewport.width === 390) }, decisions: { good: goodReport.decision, defect: defectReport.decision, corrected: correctedReport.decision, limit: limits.map((x) => x.decision) }, persistence: { qaReports: (await qa.list()).map((x) => x.id), correctionId: correction.id, correctionCount: (await corrections.list()).length }, screenshots: { desktop: good.viewports[0].screenshotPath, mobile: good.viewports[1].screenshotPath, defect: defect.viewports[0].screenshotPath, correctedDesktop: corrected.viewports[0].screenshotPath, correctedMobile: corrected.viewports[1].screenshotPath }, m006Regression: { buildSucceeded: true, replayStable: true, revisions: (await builds.list()).map((x) => x.approvedRevision) }, safety: { loopbackOnly: true, deployment: false, proposal: false, deck: false, outreach: false } }; await writeFile(resultPath, `${JSON.stringify(final, null, 2)}\n`); console.log(JSON.stringify(final, null, 2));
}
main().catch(async (error) => { const failure = { status: 'BLOCKED', failingAssertion: error instanceof Error ? error.message : String(error) }; await mkdir(join(root, 'qa'), { recursive: true }); await writeFile(resultPath, `${JSON.stringify(failure, null, 2)}\n`).catch(() => {}); console.error(error.stack || error); process.exitCode = 1; });
