import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runValidation, evaluateIdentity, classifyStage, parseCandidates, queryFor, sha256, EXPECTED_SAMPLE_HASH, SAMPLE_PATH, RESULT_PATH, MAX_REQUESTS } from './run-google-places-production-validation-v1.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const v1Path = path.join(root, 'bulk/reports/google-places-production-validation-v1-sample.json');
const v2Path = path.join(root, 'bulk/reports/google-places-production-validation-v1-sample-v2.json');
const v3Path = path.join(root, SAMPLE_PATH);
const resultPath = path.join(root, RESULT_PATH);
const response = (body, status = 200) => ({ ok: status >= 200 && status < 300, status, async text() { return typeof body === 'string' ? body : JSON.stringify(body); } });
const withKey = async (fn) => { const old = process.env.GKEY; process.env.GKEY = 'fixture-google-secret'; try { return await fn(); } finally { if (old === undefined) delete process.env.GKEY; else process.env.GKEY = old; } };
const mockFetch = async () => response({ places: [] });

test('V1_SAMPLE_PRESERVED', async () => { const v1 = JSON.parse(await fs.readFile(v1Path, 'utf8')); assert.equal(v1.sampleHash, 'ab258466159f66cbccaaa94a606a511a847b65e86e96221d90256e309ba8d969'); });
test('V2_SAMPLE_PRESERVED', async () => { const v2 = JSON.parse(await fs.readFile(v2Path, 'utf8')); assert.equal(v2.newSampleHash, '8098ad73317e254a60086713635b7925ae2bed816ce0dc75662cda7de40244f9'); });
test('V3_CONTROLS_IDENTICAL_TO_V2', async () => { const v2 = JSON.parse(await fs.readFile(v2Path, 'utf8')); const v3 = JSON.parse(await fs.readFile(v3Path, 'utf8')); assert.deepEqual(v3.controls, v2.controls); });
test('V2_V3_CONTROLS_PARSED_IDENTICAL', async () => { const v2 = JSON.parse(await fs.readFile(v2Path, 'utf8')); const v3 = JSON.parse(await fs.readFile(v3Path, 'utf8')); assert.equal(JSON.stringify(v2.controls), JSON.stringify(v3.controls)); });
test('V2_V3_CONTROLS_HASH_IDENTICAL', async () => { const v2 = JSON.parse(await fs.readFile(v2Path, 'utf8')); const v3 = JSON.parse(await fs.readFile(v3Path, 'utf8')); assert.equal(sha256(JSON.stringify(v2.controls)), sha256(JSON.stringify(v3.controls))); });
test('CANONICAL_CONTROLS_HASH_ONLY', async () => { const v3 = JSON.parse(await fs.readFile(v3Path, 'utf8')); assert.equal(v3.canonicalControlsHash, EXPECTED_SAMPLE_HASH); assert.equal(sha256(JSON.stringify(v3.controls)), EXPECTED_SAMPLE_HASH); });
test('CANONICAL_HASH_EQUALS_14DB', () => assert.equal(EXPECTED_SAMPLE_HASH, '14dbf9dcff8540ba11e2edb2dcafa599a8c867fe87080ae81d0e4d37dcca31b2'));
test('HISTORICAL_2422_NOT_USED_AS_V3_GATE', async () => { const v3 = JSON.parse(await fs.readFile(v3Path, 'utf8')); assert.equal(v3.historicalMisidentifiedHash, '2422c0b59a7fca2d51838063cb3a7b75b1f13193cb283e3b84d765ebd33319fd'); assert.notEqual(v3.canonicalControlsHash, v3.historicalMisidentifiedHash); });
test('HISTORICAL_8098_NOT_USED_AS_V3_GATE', async () => { const v3 = JSON.parse(await fs.readFile(v3Path, 'utf8')); assert.equal(v3.historicalV2DeclaredHash, '8098ad73317e254a60086713635b7925ae2bed816ce0dc75662cda7de40244f9'); assert.notEqual(v3.canonicalControlsHash, v3.historicalV2DeclaredHash); });
test('V3_RUNNER_ONLY', () => assert.equal(SAMPLE_PATH, 'bulk/reports/google-places-production-validation-v1-sample-v3.json'));
test('QUERY_INCLUDES_CANONICAL_ADDRESS', async () => { const v3 = JSON.parse(await fs.readFile(v3Path, 'utf8')); assert.equal(queryFor(v3.controls[0]), "ELECTRONIQUE +, LE LAMENTIN, Martinique, Centre Commercial Place d'Armes, 97232 Le Lamentin, Martinique"); });
test('QUERY_MAX_ONE_PER_CONTROL', async () => { let count = 0; await withKey(() => runValidation({ fetchImpl: async () => { count++; return mockFetch(); }, writeArtifact: false })); assert.equal(count, 10); });
test('REQUEST_BUDGET_MAX_10', () => assert.equal(MAX_REQUESTS, 10));
test('EXPLORATORY_SUCCESS_FIXTURE_PARSES_IN_PRODUCTION_RUNNER', () => { const parsed = parseCandidates({ places: [{ id: 'x', displayName: { text: 'ELECTRONIQUE +' }, formattedAddress: "Centre Commercial Place d'Armes, Le Lamentin 97232", nationalPhoneNumber: '0596 51 35 85' }] }); assert.equal(parsed.length, 1); assert.equal(parsed[0].name, 'ELECTRONIQUE +'); });
test('DISPLAY_NAME_OBJECT_SUPPORTED', () => assert.equal(parseCandidates({ places: [{ displayName: { text: 'KAY JUJU' } }] })[0].name, 'KAY JUJU'));
test('FORMATTED_ADDRESS_SUPPORTED', () => assert.equal(parseCandidates({ places: [{ formattedAddress: 'Le Lamentin 97232' }] })[0].address, 'Le Lamentin 97232'));
test('PHONE_DOES_NOT_INFLUENCE_IDENTITY', () => { const a = evaluateIdentity({ name: 'ELECTRONIQUE +', commune: 'LE LAMENTIN', address: '97232 Le Lamentin' }, { name: 'Wrong', address: 'Le Lamentin 97232', phone: null }); const b = evaluateIdentity({ name: 'ELECTRONIQUE +', commune: 'LE LAMENTIN', address: '97232 Le Lamentin' }, { name: 'Wrong', address: 'Le Lamentin 97232', phone: '+596596513585' }); assert.deepEqual(a, b); });
test('WRONG_ENTITY_REJECTED', () => assert.equal(evaluateIdentity({ name: 'KAY JUJU', commune: 'FORT-DE-FRANCE', address: '97200 Fort-de-France' }, { name: 'OTHER', address: 'Fort-de-France 97200' }).verdict, 'REJECTED'));
test('WRONG_BRANCH_REJECTED', () => assert.equal(evaluateIdentity({ name: 'ELECTRONIQUE +', commune: 'LE LAMENTIN', address: '97232 Le Lamentin' }, { name: 'ELECTRONIQUE +', address: 'Le Robert 97231' }).verdict, 'REJECTED'));
test('AMBIGUOUS_IDENTITY_FAILS_CLOSED', () => assert.notEqual(evaluateIdentity({ name: 'KAY JUJU', commune: 'FORT-DE-FRANCE', address: '97200 Fort-de-France' }, { name: null, address: null }).verdict, 'VERIFIED'));
test('GOOGLE_ZERO_RESULTS_DISTINGUISHED', () => assert.equal(classifyStage({ httpStatus: 200, rawPlaceCount: 0, parsedPlaceCount: 0, identityCandidateCount: 0, identityVerifiedCount: 0, identityVerdict: 'REJECTED', branchVerdict: 'NOT_EVALUATED', schemaError: false }), 'GOOGLE_ZERO_RESULTS'));
test('PARSER_ZERO_CANDIDATES_DISTINGUISHED', () => assert.equal(classifyStage({ httpStatus: 200, rawPlaceCount: 1, parsedPlaceCount: 0, identityCandidateCount: 0, identityVerifiedCount: 0, identityVerdict: 'REJECTED', branchVerdict: 'NOT_EVALUATED', schemaError: false }), 'PARSER_ZERO_CANDIDATES'));
test('IDENTITY_REJECTION_DISTINGUISHED', () => assert.equal(classifyStage({ httpStatus: 200, rawPlaceCount: 1, parsedPlaceCount: 1, identityCandidateCount: 1, identityVerifiedCount: 0, identityVerdict: 'REJECTED', branchVerdict: 'NOT_EVALUATED', schemaError: false }), 'IDENTITY_REJECTED'));
test('BRANCH_REJECTION_DISTINGUISHED', () => assert.equal(classifyStage({ httpStatus: 200, rawPlaceCount: 1, parsedPlaceCount: 1, identityCandidateCount: 1, identityVerifiedCount: 1, identityVerdict: 'VERIFIED', branchVerdict: 'REJECTED', schemaError: false }), 'BRANCH_REJECTED'));
test('VERIFIED_DISTINGUISHED', () => assert.equal(classifyStage({ httpStatus: 200, rawPlaceCount: 1, parsedPlaceCount: 1, identityCandidateCount: 1, identityVerifiedCount: 1, identityVerdict: 'VERIFIED', branchVerdict: 'MATCH', schemaError: false }), 'VERIFIED'));
test('RAW_GOOGLE_RESPONSE_NOT_PERSISTED', async () => { await withKey(async () => { await runValidation({ fetchImpl: async () => response({ places: [{ id: 'secret-place', displayName: 'Fixture' }] }), writeArtifact: true }); const out = await fs.readFile(resultPath, 'utf8'); assert.equal(out.includes('secret-place'), false); assert.equal(out.includes('Fixture'), false); }); await fs.rm(resultPath, { force: true }); });
test('GKEY_NEVER_LOGGED', async () => { let log = ''; const old = console.error; console.error = (...args) => { log += args.join(' '); }; try { await withKey(() => runValidation({ fetchImpl: async () => response({}, 403), writeArtifact: false })); } catch {} finally { console.error = old; } assert.equal(log.includes('fixture-google-secret'), false); });
test('GKEY_NEVER_PERSISTED', async () => { await withKey(async () => { await runValidation({ fetchImpl: mockFetch }); const out = await fs.readFile(resultPath, 'utf8'); assert.equal(out.includes('fixture-google-secret'), false); }); await fs.rm(resultPath, { force: true }); });
test('SANITIZED_RESULT_ONLY', async () => { await withKey(async () => { const artifact = await runValidation({ fetchImpl: mockFetch, writeArtifact: false }); assert.equal(JSON.stringify(artifact).includes('places.googleapis.com'), false); assert.equal(JSON.stringify(artifact).includes('X-Goog-Api-Key'), false); }); });
test('ZERO_TAVILY_USAGE', () => assert.equal(Boolean(process.env.TAVILY_API_KEY), false));
test('NO_CANONICAL_MUTATION', async () => { const before = await fs.readFile(v3Path, 'utf8'); await withKey(() => runValidation({ fetchImpl: mockFetch, writeArtifact: false })); assert.equal(await fs.readFile(v3Path, 'utf8'), before); });
