import assert from 'node:assert/strict';
import test from 'node:test';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import worker from './index.ts';

class SqliteD1 { constructor() { this.database = new DatabaseSync(':memory:'); this.database.exec(readFileSync(new URL('../../../database/schema.sql', import.meta.url), 'utf8')); } prepare(query) { const statement = this.database.prepare(query); let bindings = []; return { bind: (...values) => { bindings = values; return { first: async () => statement.get(...bindings) ?? null, all: async () => ({ results: statement.all(...bindings) }), run: async () => statement.run(...bindings) }; }, first: async () => statement.get(...bindings) ?? null, all: async () => ({ results: statement.all(...bindings) }), run: async () => statement.run(...bindings) }; } close() { this.database.close(); } }
const env = (db) => ({ DB: db, MAGICSCRIPT_STACK_ID: 'synthetic-stack', MAGICSCRIPT_API_TOKEN: 'synthetic-token', MAGICSCRIPT_SENDING_ENABLED: 'false', MAGICSCRIPT_EMAIL_PROVIDER: 'disabled' });
async function call(db, path, method, body) { return worker.fetch(new Request(`https://local.test${path}`, { method, headers: { authorization: 'Bearer synthetic-token', 'x-magicscript-stack-id': 'synthetic-stack', 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }), env(db)); }
const payload = { synthetic: true, fixtureId: 'synthetic-round-trip', fixtureRoot: 'D:/MagicScript/synthetic-fixtures/synthetic-round-trip', approvedLocalFixtureRoot: 'D:/MagicScript/synthetic-fixtures', internalProvenance: { source: 'INTERNAL_SYNTHETIC_FIXTURE', approvedBy: 'test', reason: 'round-trip' }, protectedFacts: { identity: 'fixture' }, protectedContract: { routes: ['/'] } };

test('API_JOB_ROUND_TRIP persists one synthetic parent and duplicate submission is idempotent', async () => { const db = new SqliteD1(); try { const first = await call(db, '/api/synthetic-creative/jobs', 'POST', { idempotencyKey: 'parent-round-trip-1', payload }); assert.equal(first.status, 201); const firstBody = await first.json(); const duplicate = await call(db, '/api/synthetic-creative/jobs', 'POST', { idempotencyKey: 'parent-round-trip-1', payload }); assert.equal(duplicate.status, 200); assert.equal((await duplicate.json()).jobId, firstBody.jobId); const row = db.database.prepare('SELECT kind, prospect_id, status, payload_json FROM jobs WHERE id = ?').get(firstBody.jobId); assert.equal(row.kind, 'CREATIVE_WEB_DESIGN_SYNTHETIC'); assert.equal(row.prospect_id, null); assert.equal(row.status, 'PENDING'); assert.equal(JSON.parse(row.payload_json).idempotencyKey, 'parent-round-trip-1'); } finally { db.close(); } });
test('API synthetic admission rejects prospect context and missing provenance', async () => { const db = new SqliteD1(); try { assert.equal((await call(db, '/api/synthetic-creative/jobs', 'POST', { idempotencyKey: 'reject-1', prospectId: 'real-prospect', payload })).status, 400); assert.equal((await call(db, '/api/synthetic-creative/jobs', 'POST', { idempotencyKey: 'reject-2', payload: { ...payload, internalProvenance: undefined } })).status, 400); } finally { db.close(); } });
