import assert from 'node:assert/strict';
import { mkdtemp, readFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildDeterministicArtifact } from '../design/design-artifact';
import { executeBuilder, BuilderError, InMemoryBuildArtifactStore } from '../builder/site-builder';
import { executeVisualQa, createBuildCorrectionRequest } from '../visual-qa/engine';
import { InMemoryBuildCorrectionStore, InMemoryVisualQaReportStore } from '../visual-qa/contracts';

function request(id: string, prospectId = `prospect-${id}`, vertical: 'RESTAURANT' | 'LOCAL_SERVICE' = 'RESTAURANT'): any { return { id: `dr-${id}-DESIGN_REQUEST_V1`, version: 'DESIGN_REQUEST_V1', prospectId, admission: { packId: `pack-${id}`, schemaVersion: 'CONTACT_OPPORTUNITY_PACK_V2' }, identity: { businessName: id === 'restaurant' ? 'Café Rivage' : 'Atelier Local' }, opportunity: { businessContext: vertical === 'RESTAURANT' ? 'Local café' : 'Local service' }, designInput: { businessVertical: vertical, evidence: [{ url: 'https://example.test', note: 'verified identity', supports: ['identity'] }] }, createdAt: '2026-01-01T00:00:00.000Z' }; }
let assertions = 0; const ok = (x: unknown, m: string) => { assert.ok(x, m); assertions++; }; const eq = (a: unknown, b: unknown, m: string) => { assert.equal(a, b, m); assertions++; };
const root = await mkdtemp(join(tmpdir(), 'm006-builder-')); const store = new InMemoryBuildArtifactStore();
const req = request('restaurant'); const artifact = { ...buildDeterministicArtifact(req, req.createdAt), status: 'APPROVED' as const }; const built = await executeBuilder({ artifact, designRequest: req, root, store });
eq(built.status, 'SUCCEEDED', 'approved artifact builds'); ok(built.sourceHash, 'source hash persisted'); ok((await stat(join(built.sourcePath, 'index.html'))).isFile(), 'source exists'); ok((await stat(join(built.outputPath, 'index.html'))).isFile(), 'output exists'); eq((await readFile(join(built.outputPath, 'index.html'), 'utf8')).includes('Café Rivage'), true, 'verified content preserved'); eq((await store.list()).length, 1, 'build artifact persisted');
const replay = await executeBuilder({ artifact, designRequest: req, root, store }); eq(replay.id, built.id, 'replay id stable'); eq(replay.sourceHash, built.sourceHash, 'replay fingerprint stable'); eq((await store.list()).length, 1, 'replay does not duplicate');
for (const status of ['DRAFT', 'CORRECTION_REQUIRED', 'REVIEW_LIMIT_REACHED'] as const) { await assert.rejects(() => executeBuilder({ artifact: { ...artifact, status }, designRequest: req, root }), (e: unknown) => e instanceof BuilderError && e.code === 'INVALID_APPROVAL_STATE'); assertions++; }
const req2 = request('service', 'prospect-service', 'LOCAL_SERVICE'); const artifact2 = { ...buildDeterministicArtifact(req2, req2.createdAt), status: 'APPROVED' as const }; const built2 = await executeBuilder({ artifact: artifact2, designRequest: req2, root, store }); ok(built2.outputPath !== built.outputPath, 'prospects isolated'); eq(artifact2.prospectId, 'prospect-service', 'linkage');
await assert.rejects(() => executeBuilder({ artifact: { ...artifact, status: 'APPROVED', prospectId: 'wrong' }, designRequest: req, root }), (e: unknown) => e instanceof BuilderError && e.code === 'INVALID_DESIGN_ARTIFACT'); assertions++;
const failureStore = new InMemoryBuildArtifactStore(); const invalidRoot = join(root, 'not-a-directory'); await (await import('node:fs/promises')).writeFile(invalidRoot, 'x'); await assert.rejects(() => executeBuilder({ artifact, designRequest: req, root: invalidRoot, store: failureStore }), (e: unknown) => e instanceof BuilderError && e.code === 'BUILD_FAILED'); assertions++; eq((await failureStore.list())[0]?.status, 'FAILED', 'build failure persisted');
const goodEvidence = { viewports: [{ name: 'DESKTOP' as const, width: 1440, height: 900, horizontalOverflow: 0, heroVisible: true, primaryCtaVisible: true, contentVisible: true, controlsWithinViewport: true }, { name: 'MOBILE' as const, width: 390, height: 844, horizontalOverflow: 0, heroVisible: true, primaryCtaVisible: true, contentVisible: true, controlsWithinViewport: true }], observedSections: ['hero', 'menu-or-offer', 'visit-information', 'location-and-contact'], brokenAssets: [], internalLinkErrors: [], unresolvedMarkers: [], consoleErrors: [], headings: ['h1 Café', 'h2 Menu'] };
const qaStore = new InMemoryVisualQaReportStore(); const goodQa = await executeVisualQa({ build: built, design: artifact, request: req, evidence: goodEvidence, store: qaStore }); eq(goodQa.decision, 'PASS', 'good rendered build passes QA'); eq((await qaStore.list()).length, 1, 'QA persisted'); const replayQa = await executeVisualQa({ build: built, design: artifact, request: req, evidence: goodEvidence, store: qaStore }); eq(replayQa.id, goodQa.id, 'QA replay idempotent');
const badQa = await executeVisualQa({ build: built, design: artifact, request: req, evidence: { ...goodEvidence, viewports: [{ ...goodEvidence.viewports[1], horizontalOverflow: 80, primaryCtaVisible: false }] }, attempt: 1 }); eq(badQa.decision, 'CORRECTION_REQUIRED', 'mobile regression detected'); const correctionStore = new InMemoryBuildCorrectionStore(); const correction = createBuildCorrectionRequest(badQa); await correctionStore.save(correction); await correctionStore.save(createBuildCorrectionRequest(badQa)); eq((await correctionStore.list()).length, 1, 'correction replay idempotent'); const limited = await executeVisualQa({ build: built, design: artifact, request: req, evidence: { ...goodEvidence, unresolvedMarkers: ['debug'] }, attempt: 3 }); eq(limited.decision, 'VISUAL_QA_LIMIT_REACHED', 'QA limit does not auto-pass');
console.log(JSON.stringify({ ok: true, assertions, outputs: [built.outputPath, built2.outputPath] }));
