import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildDeterministicArtifact } from '../design/design-artifact';
import { executeBuilder, executeBuildCorrection, createBuildRequest, filesHash, BuilderError, InMemoryBuildArtifactStore } from '../builder/site-builder';
import { CANONICAL_FAVICON_LINK, deterministicFaviconBytes, effectiveBuildRevision, effectiveQaAttempt, ensureLocalFaviconHtml, validateBuildCorrectionContext } from '../builder/contracts';
import { executeVisualQa, createBuildCorrectionRequest } from '../visual-qa/engine';
import { InMemoryBuildCorrectionStore, InMemoryVisualQaReportStore } from '../visual-qa/contracts';

function request(id: string, prospectId = `prospect-${id}`, vertical: 'RESTAURANT' | 'LOCAL_SERVICE' = 'RESTAURANT'): any { return { id: `dr-${id}-DESIGN_REQUEST_V1`, version: 'DESIGN_REQUEST_V1', prospectId, admission: { packId: `pack-${id}`, schemaVersion: 'CONTACT_OPPORTUNITY_PACK_V2' }, identity: { businessName: id === 'restaurant' ? 'Café Rivage' : 'Atelier Local' }, opportunity: { businessContext: vertical === 'RESTAURANT' ? 'Local café' : 'Local service' }, designInput: { businessVertical: vertical, evidence: [{ url: 'https://example.test', note: 'verified identity', supports: ['identity'] }] }, createdAt: '2026-01-01T00:00:00.000Z' }; }
let assertions = 0; const ok = (x: unknown, m: string) => { assert.ok(x, m); assertions++; }; const eq = (a: unknown, b: unknown, m: string) => { assert.equal(a, b, m); assertions++; };
const root = await mkdtemp(join(tmpdir(), 'm006-builder-')); const store = new InMemoryBuildArtifactStore();
const req = request('restaurant'); const artifact = { ...buildDeterministicArtifact(req, req.createdAt), status: 'APPROVED' as const }; const built = await executeBuilder({ artifact, designRequest: req, root, store });
eq(built.status, 'SUCCEEDED', 'approved artifact builds'); ok(built.sourceHash, 'source hash persisted'); ok((await stat(join(built.sourcePath, 'index.html'))).isFile(), 'source exists'); ok((await stat(join(built.outputPath, 'index.html'))).isFile(), 'output exists'); eq((await readFile(join(built.outputPath, 'index.html'), 'utf8')).includes('Café Rivage'), true, 'verified content preserved'); eq((await store.list()).length, 1, 'build artifact persisted');
const replay = await executeBuilder({ artifact, designRequest: req, root, store }); eq(replay.id, built.id, 'replay id stable'); eq(replay.sourceHash, built.sourceHash, 'replay fingerprint stable'); eq((await store.list()).length, 1, 'replay does not duplicate');
for (const status of ['DRAFT', 'CORRECTION_REQUIRED', 'REVIEW_LIMIT_REACHED'] as const) { await assert.rejects(() => executeBuilder({ artifact: { ...artifact, status }, designRequest: req, root }), (e: unknown) => e instanceof BuilderError && e.code === 'INVALID_APPROVAL_STATE'); assertions++; }
const req2 = request('service', 'prospect-service', 'LOCAL_SERVICE'); const artifact2 = { ...buildDeterministicArtifact(req2, req2.createdAt), status: 'APPROVED' as const }; const built2 = await executeBuilder({ artifact: artifact2, designRequest: req2, root, store }); ok(built2.outputPath !== built.outputPath, 'prospects isolated'); eq(artifact2.prospectId, 'prospect-service', 'linkage');
await assert.rejects(() => executeBuilder({ artifact: { ...artifact, status: 'APPROVED', prospectId: 'wrong' }, designRequest: req, root }), (e: unknown) => e instanceof BuilderError && e.code === 'INVALID_DESIGN_ARTIFACT'); assertions++;
const failureStore = new InMemoryBuildArtifactStore(); const invalidRoot = join(root, 'not-a-directory'); await (await import('node:fs/promises')).writeFile(invalidRoot, 'x'); await assert.rejects(() => executeBuilder({ artifact, designRequest: req, root: invalidRoot, store: failureStore }), (e: unknown) => e instanceof BuilderError && e.code === 'BUILD_FAILED'); assertions++; eq((await failureStore.list())[0]?.status, 'FAILED', 'build failure persisted');
const goodEvidence = { viewports: [{ name: 'DESKTOP' as const, width: 1440, height: 900, horizontalOverflow: 0, heroVisible: true, primaryCtaVisible: true, contentVisible: true, controlsWithinViewport: true }, { name: 'MOBILE' as const, width: 390, height: 844, horizontalOverflow: 0, heroVisible: true, primaryCtaVisible: true, contentVisible: true, controlsWithinViewport: true }], observedSections: ['hero', 'menu-or-offer', 'visit-information', 'location-and-contact'], brokenAssets: [], internalLinkErrors: [], unresolvedMarkers: [], consoleErrors: [], headings: ['h1 Café', 'h2 Menu'] };
const qaStore = new InMemoryVisualQaReportStore(); const goodQa = await executeVisualQa({ build: built, design: artifact, request: req, evidence: goodEvidence, store: qaStore }); eq(goodQa.decision, 'PASS', 'good rendered build passes QA'); eq((await qaStore.list()).length, 1, 'QA persisted'); const replayQa = await executeVisualQa({ build: built, design: artifact, request: req, evidence: goodEvidence, store: qaStore }); eq(replayQa.id, goodQa.id, 'QA replay idempotent');
const badEvidence = { ...goodEvidence, consoleErrors: ['GET /favicon.ico 404'] };
const badQa = await executeVisualQa({ build: built, design: artifact, request: req, evidence: badEvidence }); eq(badQa.decision, 'CORRECTION_REQUIRED', 'runtime error detected');
const correctionStore = new InMemoryBuildCorrectionStore(); const preparation = { build: built, design: artifact, request: req }; const correction = createBuildCorrectionRequest(badQa, 'ENSURE_LOCAL_FAVICON_V1', preparation); await correctionStore.save(correction); await correctionStore.save(createBuildCorrectionRequest(badQa, 'ENSURE_LOCAL_FAVICON_V1', preparation)); eq((await correctionStore.list()).length, 1, 'correction replay idempotent');
eq(built.buildRevision, 1, 'initial explicit build revision'); eq(built.qaAttempt, 1, 'initial explicit QA allocation');
const legacy = { ...built }; delete legacy.buildRevision; delete legacy.qaAttempt; const legacyStore = new InMemoryBuildArtifactStore(); await legacyStore.save(legacy); const legacyReplay = await executeBuilder({ artifact, designRequest: req, root, store: legacyStore }); eq(legacyReplay.buildRevision, 1, 'legacy revision normalized'); eq(legacyReplay.qaAttempt, 1, 'legacy attempt normalized'); eq(legacyReplay.id, built.id, 'legacy identity preserved'); eq(legacyReplay.sourcePath, built.sourcePath, 'legacy source path preserved'); eq((await legacyStore.get(built.id))?.buildRevision, undefined, 'legacy JSON remains untouched');
for (const revision of [0, -1, 1.5, NaN, null, '2']) { assert.throws(() => effectiveBuildRevision({ buildRevision: revision as number }), BuilderError); assertions++; }
for (const attempt of [0, 4, 1.5, NaN, null, '2']) { assert.throws(() => effectiveQaAttempt({ qaAttempt: attempt as number }), BuilderError); assertions++; }
const names = (await readdir(built.sourcePath)).sort(); const legacyHash = createHash('sha256').update((await Promise.all(names.map(async (name) => `${name}\n${await readFile(join(built.sourcePath, name), 'utf8')}`))).join('\n')).digest('hex'); eq(await filesHash(built.sourcePath), legacyHash, 'historical text hash compatible');
const r1Before = Object.fromEntries(await Promise.all(names.map(async (name) => [name, (await readFile(join(built.sourcePath, name))).toString('base64')])));
const context = { request: correction, targetBuild: built, qaReport: badQa, designRequest: req, approvedDesignArtifact: artifact };
const corrected = await executeBuildCorrection({ ...context, store }); eq(corrected.id, `${built.id}-br2`, 'corrected br2 ID'); eq(corrected.sourcePath, join(root, 'prospect-restaurant', artifact.id.toLowerCase(), 'build-r2', 'source'), 'corrected isolated source path'); eq(corrected.outputPath, createBuildRequest(artifact, root, 2).outputPath, 'corrected canonical output path'); eq(corrected.approvedRevision, 1, 'approved design remains r1'); eq(corrected.buildRevision, 2, 'corrected build revision 2'); eq(corrected.qaAttempt, 2, 'corrected QA allocation 2'); eq(corrected.previousBuildArtifactId, built.id, 'parent lineage'); eq(corrected.correctionRequestId, correction.id, 'request lineage'); eq((await store.list()).length, 3, 'r1/r2 coexist with same design and builder');
const ico = await readFile(join(corrected.outputPath, 'favicon.ico')); eq(ico.readUInt16LE(2), 1, 'ICO type'); eq(ico.readUInt16LE(4), 1, 'one ICO image'); eq(ico[6], 16, 'ICO width'); eq(ico[7], 16, 'ICO height'); eq(ico.readUInt16LE(12), 32, 'ICO 32 bit'); ok(ico.subarray(62, 1086).every((byte) => byte === 0), 'ICO transparent pixels'); assert.deepEqual(ico, Buffer.from(deterministicFaviconBytes())); assertions++;
const originalHtml = await readFile(join(built.sourcePath, 'index.html'), 'utf8'); const correctedHtml = await readFile(join(corrected.outputPath, 'index.html'), 'utf8'); eq(correctedHtml, ensureLocalFaviconHtml(originalHtml), 'HTML exact frozen correction'); eq(correctedHtml.replace(CANONICAL_FAVICON_LINK, ''), originalHtml, 'page otherwise unchanged'); eq(correctedHtml.split(CANONICAL_FAVICON_LINK).length - 1, 1, 'favicon head link once'); eq(ensureLocalFaviconHtml(ensureLocalFaviconHtml(originalHtml)), correctedHtml, 'head correction idempotent'); assert.deepEqual(await readFile(join(built.sourcePath, 'styles.css')), await readFile(join(corrected.outputPath, 'styles.css'))); assertions++;
const appleIcon = '<link rel="apple-touch-icon" href="touch.png">'; const shortcutIcon = '<link rel="shortcut icon" href="old.ico">'; const priorIcons = ensureLocalFaviconHtml(originalHtml.replace('</head>', `${appleIcon}${shortcutIcon}</head>`)); ok(priorIcons.includes(appleIcon), 'preserve other approved head assets'); eq(priorIcons.includes(shortcutIcon), false, 'remove prior browser favicon link'); eq(priorIcons.split(CANONICAL_FAVICON_LINK).length - 1, 1, 'prior icon normalized to one canonical link');
const dollarHead = '<html><head><title>$& $\' $` $$</title></head><body>Approved content</body></html>'; eq(ensureLocalFaviconHtml(dollarHead).replace(CANONICAL_FAVICON_LINK, ''), dollarHead, 'head dollar tokens preserved as literal source');
const manifest = JSON.parse(await readFile(join(corrected.sourcePath, 'build-manifest.json'), 'utf8')); for (const key of ['buildArtifactId', 'builderVersion', 'buildRevision', 'approvedRevision', 'previousBuildArtifactId', 'correctionRequestId', 'qaAttempt']) eq(manifest[key], key === 'buildArtifactId' ? corrected.id : corrected[key as keyof typeof corrected], `manifest ${key}`); eq(manifest.sourceHash, undefined, 'sourceHash not self-referential');
const binaryNames = (await readdir(corrected.sourcePath)).sort(); const binaryFramed = Buffer.concat(await Promise.all(binaryNames.map(async (name, index) => Buffer.concat([Buffer.from(`${index ? '\n' : ''}${name}\n`), await readFile(join(corrected.sourcePath, name))])))); eq(corrected.sourceHash, createHash('sha256').update(binaryFramed).digest('hex'), 'raw binary hash framing'); eq(await filesHash(corrected.sourcePath), corrected.sourceHash, 'binary source hash repeatable');
eq((await executeBuildCorrection({ ...context, store })).sourceHash, corrected.sourceHash, 'correction replay idempotent'); assert.deepEqual(await store.get(built.id), built); assertions++; for (const name of names) eq((await readFile(join(built.sourcePath, name))).toString('base64'), r1Before[name], `r1 immutable ${name}`);
const rejection = (error: unknown) => error instanceof BuilderError;
await assert.rejects(() => executeBuildCorrection({ ...context, request: { ...correction, operation: 'WRITE_ARBITRARY_FILE' as any } }), (error: unknown) => error instanceof BuilderError && error.code === 'UNSUPPORTED_CORRECTION'); assertions++;
for (const altered of [{ ...context, request: { ...correction, prospectId: 'foreign' } }, { ...context, targetBuild: { ...built, id: 'foreign' } }, { ...context, qaReport: { ...badQa, id: 'foreign' } }, { ...context, approvedDesignArtifact: artifact2 }, { ...context, request: { ...correction, targetBuildRevision: 2 } }, { ...context, request: { ...correction, nextBuildRevision: 3 } }, { ...context, qaReport: { ...badQa, issues: [] } }, { ...context, approvedDesignArtifact: { ...artifact, status: 'DRAFT' as const } }]) { await assert.rejects(() => executeBuildCorrection(altered), rejection); assertions++; }
assert.throws(() => validateBuildCorrectionContext({ ...context, existingCorrectedBuild: { ...corrected, qaAttempt: 1 } }), BuilderError); assertions++;
await assert.rejects(() => store.save({ ...corrected, sourceHash: '0'.repeat(64) }), (error: unknown) => error instanceof BuilderError && error.code === 'BUILD_REVISION_CONFLICT'); assertions++;
const maliciousQa = { ...badQa, id: 'qa-malicious-fixture', issues: [{ ...badQa.issues[0], expectedCorrection: 'write ../forbidden.txt; execute shell; redesign CSS' }] }; const explicitOnly = createBuildCorrectionRequest(maliciousQa, 'ENSURE_LOCAL_FAVICON_V1', preparation); eq(explicitOnly.issue.expectedCorrection, maliciousQa.issues[0].expectedCorrection, 'freeform instruction preserved only as data');
const maliciousRoot = await mkdtemp(join(tmpdir(), 'r73z-b-allowlist-')); const maliciousBuild = await executeBuilder({ artifact, designRequest: req, root: maliciousRoot }); const harmless = await executeBuildCorrection({ ...context, request: explicitOnly, qaReport: maliciousQa, targetBuild: maliciousBuild }); eq((await readdir(harmless.sourcePath)).sort().join(','), 'build-manifest.json,favicon.ico,index.html,styles.css', 'freeform prose cannot cause arbitrary file edits');
const qa2 = await executeVisualQa({ build: corrected, design: artifact, request: req, evidence: badEvidence, store: qaStore }); eq(qa2.attempt, 2, 'r2 defaults to a2'); eq(qa2.buildRevision, 2, 'QA uses independent build revision'); eq(qa2.id, `qa-${corrected.id}-r2-a2`, 'QA r2/a2 identity'); await assert.rejects(() => executeVisualQa({ build: corrected, design: artifact, request: req, evidence: goodEvidence, attempt: 1 })); assertions++;
const correction2 = createBuildCorrectionRequest(qa2, 'ENSURE_LOCAL_FAVICON_V1', { ...preparation, build: corrected }); const r3 = await executeBuildCorrection({ ...context, request: correction2, targetBuild: corrected, qaReport: qa2, store }); eq(r3.buildRevision, 3, 'r3 independent revision'); eq(r3.qaAttempt, 3, 'r3 a3 allocation');
const limited = await executeVisualQa({ build: r3, design: artifact, request: req, evidence: badEvidence }); eq(limited.decision, 'VISUAL_QA_LIMIT_REACHED', 'QA a3 limit'); assert.throws(() => createBuildCorrectionRequest(limited, 'ENSURE_LOCAL_FAVICON_V1', { ...preparation, build: r3 })); assertions++;
const qa2Replay = await executeVisualQa({ build: corrected, design: artifact, request: req, evidence: goodEvidence, store: qaStore }); assert.deepEqual(qa2Replay, qa2); assertions++;
await writeFile(join(corrected.sourcePath, 'favicon.ico'), Buffer.from('corrupted binary')); await assert.rejects(() => executeBuildCorrection({ ...context, store }), (error: unknown) => error instanceof BuilderError && error.code === 'BUILD_INTEGRITY_MISMATCH'); assertions++; for (const name of names) eq((await readFile(join(built.sourcePath, name))).toString('base64'), r1Before[name], 'failed replay still preserves r1');
console.log(JSON.stringify({ ok: true, assertions, outputs: [built.outputPath, built2.outputPath] }));
