import test from 'node:test';
import assert from 'node:assert/strict';
import { commercialFixtures } from './fixtures/agent3-commercial/fixtures';
import { projectCommercialCatalog } from '../outreach/commercial-catalog';
import { createCommercialPreparationContext, deserializeCommercialPreparationContext, commercialPreparationContextIssues, mapTrustedVertical, serializeCommercialPreparationContext } from '../outreach/commercial-preparation-context';
import { InMemoryCommercialPreparationContextStore, D1CommercialPreparationContextStore } from '../persistence/d1-commercial-preparation-context-store';

const source = commercialFixtures[0].context;
const proposal = { id: 'proposal-context-1', version: 'PROPOSAL_V1' as const, prospectId: source.prospect.id, designRequestId: 'design-1', approvedDesignArtifactId: 'artifact-1', approvedDesignRevision: 1, buildArtifactId: 'build-1', buildRevision: 2, visualQaReportId: 'qa-1', token: 'token-1', entryPath: '/p/token-1', status: 'PROPOSAL_READY' as const, createdAt: '2026-09-01T12:00:00Z', booking: { availabilityPath: '/availability', bookingPath: '/booking' }, tracking: { sessionCookie: 'cookie', events: ['PROPOSAL_VIEWED'] as const } };
function make() { return createCommercialPreparationContext({ prospectId: source.prospect.id, proposal, createdAt: '2026-09-01T12:00:00Z', evaluatedAt: source.evaluatedAt, agent1: source.agent1 as never, verticalEvidence: 'restaurant', commercialState: 'STANDARD', sources: structuredClone(source.sources), claims: structuredClone(source.claims), requiredClaimIds: [...source.requiredClaimIds], derivationRules: structuredClone(source.derivationRules), channel: { type: source.channel, contactRef: 'contact-authority', sourceRef: 'channel-authority', verifiedAt: source.evaluatedAt }, contactState: { suppressionAuthorityRef: 'suppression-authority', firstContactAuthorityRef: 'first-contact-authority', sourceRef: 'contact-state-authority', verifiedAt: source.evaluatedAt }, catalogEntries: projectCommercialCatalog(['STARTER']), scopeConfirmed: true }); }

test('projects trusted claims, opportunity, proposal, vertical and catalog authority', () => { const context = make(); assert.equal(context.schemaVersion, 1); assert.equal(context.vertical.profile, 'RESTAURANTS_BARS_CAFES'); assert.deepEqual(context.agent1.opportunity.supportingClaimIds, source.agent1.opportunity!.supportingClaimIds); assert.equal(context.artifact.proposalId, proposal.id); assert.equal(context.catalog.entries[0].amountCents, 79000); assert.deepEqual(commercialPreparationContextIssues(context), []); });
test('unknown vertical deterministically becomes neutral', () => { assert.equal(mapTrustedVertical('ambiguous local business'), 'NEUTRAL_EVIDENCE_ONLY'); });
test('construction state is evidence gated', () => { const context = make(); context.commercialState = 'SITE_UNDER_CONSTRUCTION'; assert.ok(commercialPreparationContextIssues(context).includes('SITE_STATE_UNSUPPORTED')); });
test('round trip preserves exact serialized authority and malformed data fails closed', () => { const context = make(); const serialized = serializeCommercialPreparationContext(context); assert.equal(serializeCommercialPreparationContext(deserializeCommercialPreparationContext(serialized)), serialized); assert.throws(() => deserializeCommercialPreparationContext('{bad'), /MALFORMED/); });
test('in-memory store rejects immutable overwrite and reloads exact snapshot', async () => { const context = make(); const store = new InMemoryCommercialPreparationContextStore(); await store.saveCommercialPreparationContext(context); assert.deepEqual(await store.getCommercialPreparationContext(context.contextId), context); const changed = structuredClone(context); changed.agent1.version = 'changed'; await assert.rejects(() => store.saveCommercialPreparationContext(changed), /IMMUTABLE_CONTEXT_CONFLICT/); });
test('D1 store uses append-only JSON persistence and reloads after a fresh instance', async () => { const context = make(); const rows = new Map<string, any>(); const queries: string[] = []; const db = { prepare(query: string) { queries.push(query); let bound: unknown[] = []; return { bind(...values: unknown[]) { bound = values; return this; }, async first<T>() { const row = rows.get(String(bound[0])); return row ? row as T : null; }, async all<T>() { return { results: [] as T[] }; }, async run() { rows.set(String(bound[0]), { context_json: bound[5] }); return { meta: { changes: 1 } }; } }; } }; const store = new D1CommercialPreparationContextStore(db); await store.saveCommercialPreparationContext(context); const fresh = new D1CommercialPreparationContextStore(db); assert.deepEqual(await fresh.getCommercialPreparationContext(context.contextId), context); assert.match(queries[0], /INSERT INTO v2_commercial_preparation_contexts/); assert.match(queries[0], /ON CONFLICT\(context_id\) DO NOTHING/); });
test('proposal mismatch and unsupported source are rejected', () => { const bad = structuredClone(source); bad.sources[0].prospectId = 'other'; assert.throws(() => createCommercialPreparationContext({ prospectId: source.prospect.id, proposal, createdAt: '2026-09-01T12:00:00Z', evaluatedAt: source.evaluatedAt, agent1: source.agent1 as never, verticalEvidence: 'restaurant', commercialState: 'STANDARD', sources: bad.sources, claims: bad.claims, requiredClaimIds: [...bad.requiredClaimIds], derivationRules: bad.derivationRules, channel: { type: source.channel, contactRef: 'c', sourceRef: 's', verifiedAt: source.evaluatedAt }, contactState: { suppressionAuthorityRef: 's', firstContactAuthorityRef: 'f', sourceRef: 'h', verifiedAt: source.evaluatedAt }, catalogEntries: projectCommercialCatalog(['STARTER']), scopeConfirmed: true }), /INVALID_COMMERCIAL_PREPARATION_CONTEXT/); });
