import test from 'node:test';
import assert from 'node:assert/strict';
import { buildDeterministicArtifact, InMemoryDesignArtifactStore } from '../design/design-artifact';
import { executeDesignDirector } from '../design/design-director';
import { InMemoryCorrectionStore, InMemoryDesignReviewStore, MAX_DESIGN_REVISIONS } from '../design/design-review';
import type { DesignRequestV1 } from '../design/design-request';
import { InMemoryJobQueue } from '../jobs/in-memory-queue';

const request: DesignRequestV1 = { id: 'dr-test-DESIGN_REQUEST_V1', version: 'DESIGN_REQUEST_V1', prospectId: 'p-test', admission: { packId: 'pack-test', schemaVersion: 'CONTACT_OPPORTUNITY_PACK_V2' }, identity: { businessName: 'Maison Test' }, opportunity: { businessContext: 'Local café' }, designInput: { businessVertical: 'RESTAURANT', evidence: [{ url: 'https://example.test', note: 'Observed', supports: ['identity'] }] }, createdAt: '2026-01-01T00:00:00.000Z' };

test('director independently approves grounded deterministic artifact and replay is idempotent', async () => { const artifacts = new InMemoryDesignArtifactStore(); const artifact = buildDeterministicArtifact(request, '2026-01-01T00:00:00.000Z'); await artifacts.save(artifact); const reviews = new InMemoryDesignReviewStore(); const corrections = new InMemoryCorrectionStore(); const jobs = new InMemoryJobQueue(); const deps = { artifacts, reviews, corrections, jobs, now: () => new Date('2026-01-01T01:00:00.000Z') }; const first = await executeDesignDirector({ request, artifact, deps }); const second = await executeDesignDirector({ request, artifact, deps }); assert.equal(first.review.decision, 'APPROVE'); assert.equal(second.review.id, first.review.id); assert.equal((await reviews.list()).length, 1); assert.equal((await jobs.list()).length, 0); });

test('director emits correction and one revision job for unsupported claim', async () => { const artifact = { ...buildDeterministicArtifact(request, '2026-01-01T00:00:00.000Z'), pages: [{ ...buildDeterministicArtifact(request, '2026-01-01T00:00:00.000Z').pages[0], content: [{ kind: 'VERIFIED_FACT' as const, text: 'Award-winning since 1990' }] }] }; const artifacts = new InMemoryDesignArtifactStore(); await artifacts.save(artifact); const reviews = new InMemoryDesignReviewStore(); const corrections = new InMemoryCorrectionStore(); const jobs = new InMemoryJobQueue(); const result = await executeDesignDirector({ request, artifact, deps: { artifacts, reviews, corrections, jobs } }); assert.equal(result.review.decision, 'CORRECT'); assert.ok(result.correction); assert.equal((await corrections.list()).length, 1); assert.equal((await jobs.list()).filter((j) => j.kind === 'V2_DESIGN_REVISION').length, 1); });

test('maximum revision does not auto approve', async () => { const artifact = { ...buildDeterministicArtifact(request, '2026-01-01T00:00:00.000Z'), id: `artifact-${request.id}-DESIGN_ARTIFACT_V1-r${MAX_DESIGN_REVISIONS}`, revision: MAX_DESIGN_REVISIONS, pages: [{ ...buildDeterministicArtifact(request, '2026-01-01T00:00:00.000Z').pages[0], content: [{ kind: 'VERIFIED_FACT' as const, text: 'Award-winning since 1990' }] }] }; const result = await executeDesignDirector({ request, artifact, deps: { artifacts: new InMemoryDesignArtifactStore(), reviews: new InMemoryDesignReviewStore(), corrections: new InMemoryCorrectionStore() } }); assert.equal(result.review.decision, 'CORRECT'); assert.equal(result.terminalStatus, 'REVIEW_LIMIT_REACHED'); });
