export interface CommercialExemplar { id: string; context: Record<string, unknown>; supportedClaims: string[]; channel: 'EMAIL' | 'MOBILE'; expectedTextCharacteristics: string[]; teachingAnnotations: string[]; playbookVersion: 'AGENT3_COMMERCIAL_PLAYBOOK_V1'; }
const base = { playbookVersion: 'AGENT3_COMMERCIAL_PLAYBOOK_V1' as const };
export const COMMERCIAL_EXEMPLARS: readonly CommercialExemplar[] = [
 { ...base, id: 'cp03-restaurant-email', context: { vertical: 'RESTAURANTS_BARS_CAFES' }, supportedClaims: ['public menu observation'], channel: 'EMAIL', expectedTextCharacteristics: ['grounded', 'demo-led', 'one reaction CTA'], teachingAnnotations: ['specificity without promise'], },
 { ...base, id: 'cp03-beauty-mobile', context: { vertical: 'BEAUTY_HAIR_BARBER' }, supportedClaims: ['public service detail'], channel: 'MOBILE', expectedTextCharacteristics: ['immediate identity', 'short question'], teachingAnnotations: ['mobile is independently composed'], },
 { ...base, id: 'cp03-retail-email', context: { vertical: 'LOCAL_RETAIL' }, supportedClaims: ['public product/range detail'], channel: 'EMAIL', expectedTextCharacteristics: ['natural paragraphs', 'one demo link'], teachingAnnotations: ['do not imply e-commerce'], },
 { ...base, id: 'cp03-services-mobile', context: { vertical: 'LOCAL_SERVICES' }, supportedClaims: ['public service-area detail'], channel: 'MOBILE', expectedTextCharacteristics: ['conversational', 'no signoff'], teachingAnnotations: ['no guaranteed lead claim'], },
 { ...base, id: 'cp03-strong-site-email', context: { vertical: 'LOCAL_RETAIL', siteQuality: 'strong' }, supportedClaims: ['recognizable business detail'], channel: 'EMAIL', expectedTextCharacteristics: ['positive angle', 'factual restraint'], teachingAnnotations: ['strong site is not a reason to invent a gap'], },
 { ...base, id: 'cp03-generic-correction', context: { defect: 'generic' }, supportedClaims: ['supported observation'], channel: 'EMAIL', expectedTextCharacteristics: ['corrected specific opening'], teachingAnnotations: ['rewrite, never add facts'], },
 { ...base, id: 'cp03-aggressive-correction', context: { defect: 'aggressive' }, supportedClaims: ['supported observation'], channel: 'EMAIL', expectedTextCharacteristics: ['calm opposition'], teachingAnnotations: ['remove urgency and pressure'], },
 { ...base, id: 'cp03-fake-feature-correction', context: { defect: 'fake-live-feature' }, supportedClaims: ['demonstrative capability'], channel: 'EMAIL', expectedTextCharacteristics: ['honest demonstration wording'], teachingAnnotations: ['never upgrade demonstrative to live'], },
 { ...base, id: 'cp03-price-correction', context: { defect: 'wrong-price' }, supportedClaims: [], channel: 'EMAIL', expectedTextCharacteristics: ['no price by default'], teachingAnnotations: ['catalog authority only; no package recommendation'], },
 { ...base, id: 'cp03-familiarity-correction', context: { defect: 'fake-familiarity' }, supportedClaims: ['public observation'], channel: 'EMAIL', expectedTextCharacteristics: ['no implied relationship'], teachingAnnotations: ['first contact remains first contact'], },
 { ...base, id: 'cp03-suppression', context: { suppression: 'DO_NOT_CONTACT' }, supportedClaims: [], channel: 'EMAIL', expectedTextCharacteristics: ['no candidate'], teachingAnnotations: ['suppression is a blocker'], },
 { ...base, id: 'cp03-ambiguous-abstention', context: { evidence: 'ambiguous' }, supportedClaims: [], channel: 'MOBILE', expectedTextCharacteristics: ['no candidate'], teachingAnnotations: ['unknown stays unknown'], },
];
if (COMMERCIAL_EXEMPLARS.length !== 12) throw new Error('CP03 exemplar count must remain exactly 12');
